/**
 *
 * AuthRest.cc
 * This file is generated by drogon_ctl
 *
 */

#include "AuthRest.h"
#include <string>
#include "plugins/SodiumPlugin.h"
#include <drogon/HttpResponse.h>
#include <drogon/HttpTypes.h>
#include <drogon/orm/DbClient.h>
#include <drogon/orm/Result.h>
#include <drogon/orm/Exception.h> 

void AuthRest::getOne(const HttpRequestPtr &req,
                      std::function<void(const HttpResponsePtr &)> &&callback,
                      std::string &&id)
{
    auto resp = drogon::HttpResponse::newHttpResponse();
    resp->setStatusCode(drogon::k404NotFound);
    callback(resp);
}

void AuthRest::get(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback)
{
    auto resp = drogon::HttpResponse::newHttpResponse();
    resp->setStatusCode(drogon::k404NotFound);
    callback(resp);
}

void AuthRest::create(const HttpRequestPtr &req,
                      std::function<void(const HttpResponsePtr &)> &&callback)
{
    auto json = req->getJsonObject();
    if (!json) {
        auto resp = drogon::HttpResponse::newHttpResponse();
        resp->setStatusCode(drogon::k400BadRequest);
        callback(resp);
        return;
    }

    auto *auth = drogon::app().getPlugin<SodiumPlugin>();
    if (!auth) {
        LOG_ERROR << "SodiumPlugin not loaded!";
        auto resp = drogon::HttpResponse::newHttpResponse();
        resp->setStatusCode(drogon::k500InternalServerError);
        callback(resp);
        return;
    }

    // SAFE EXTRACTION: Use .get() with a default value to prevent LogicError if key is missing
    std::string type = json->get("type", "").asString(); 
    std::string email = json->get("email", "").asString();
    std::string password = json->get("password", "").asString();

    auto dbClient = drogon::app().getDbClient();

    if (type == "signup") {
        std::string username = json->get("username", "").asString();
        
        if (username.empty() || email.empty() || password.empty()) {
            auto resp = drogon::HttpResponse::newHttpResponse();
            resp->setStatusCode(drogon::k400BadRequest);
            callback(resp);
            return;
        }

        std::string hashed = auth->hashPassword(password); 

        dbClient->execSqlAsync(
            "INSERT INTO Users (username, email, password_hash) VALUES ($1, $2, $3)",
            [callback](const drogon::orm::Result &res) {
                // EXPLICIT CONSTRUCTION: Avoids initializer list constructor bugs
                Json::Value ret;
                ret["result"] = "ok";
                auto resp = drogon::HttpResponse::newHttpJsonResponse(ret);
                resp->setStatusCode(drogon::k201Created);
                callback(resp);
            },
            [callback](const drogon::orm::DrogonDbException &e) {
                LOG_ERROR << e.base().what();
                auto resp = drogon::HttpResponse::newHttpResponse();
                resp->setStatusCode(drogon::k500InternalServerError);
                callback(resp);
            },
            username, email, hashed);
    }
    else if (type == "login") {
        if (email.empty() || password.empty()) {
            auto resp = drogon::HttpResponse::newHttpResponse();
            resp->setStatusCode(drogon::k400BadRequest);
            callback(resp);
            return;
        }

        dbClient->execSqlAsync(
            "SELECT password_hash FROM Users WHERE email = $1",
            [auth, callback, password](const drogon::orm::Result &res) {
                if (res.size() > 0) {
                    std::string storedHash = res[0]["password_hash"].as<std::string>();
                    
                    if (auth->verifyPassword(password, storedHash)) {
                        Json::Value ret;
                        ret["result"] = "ok";
                        ret["token"] = "valid_token_placeholder";
                        auto resp = drogon::HttpResponse::newHttpJsonResponse(ret);
                        resp->setStatusCode(drogon::k200OK);
                        callback(resp);
                        return;
                    }
                }
                auto resp = drogon::HttpResponse::newHttpResponse();
                resp->setStatusCode(drogon::k401Unauthorized);
                callback(resp);
            },
            [callback](const drogon::orm::DrogonDbException &e) {
                auto resp = drogon::HttpResponse::newHttpResponse();
                resp->setStatusCode(drogon::k500InternalServerError);
                callback(resp);
            },
            email
        );
    }
    else {
        auto resp = drogon::HttpResponse::newHttpResponse();
        resp->setStatusCode(drogon::k400BadRequest);
        callback(resp);
    }
}

void AuthRest::updateOne(const HttpRequestPtr &req,
                         std::function<void(const HttpResponsePtr &)> &&callback,
                         std::string &&id)
{
    auto resp = drogon::HttpResponse::newHttpResponse();
    resp->setStatusCode(drogon::k404NotFound);
    callback(resp);
}

void AuthRest::deleteOne(const HttpRequestPtr &req,
                         std::function<void(const HttpResponsePtr &)> &&callback,
                         std::string &&id)
{
    auto resp = drogon::HttpResponse::newHttpResponse();
    resp->setStatusCode(drogon::k404NotFound);
    callback(resp);
}