/**
 *
 *  FoodItems.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "FoodItems.h"
#include <string>


void FoodItems::getOne(const HttpRequestPtr &req,
                       std::function<void(const HttpResponsePtr &)> &&callback,
                       std::string &&id)
{
}

void FoodItems::get(const HttpRequestPtr &req,
                    std::function<void(const HttpResponsePtr &)> &&callback)
{
}
void FoodItems::create(const HttpRequestPtr &req,
                       std::function<void(const HttpResponsePtr &)> &&callback)
{
}
void FoodItems::updateOne(const HttpRequestPtr &req,
                          std::function<void(const HttpResponsePtr &)> &&callback,
                          std::string &&id)
{
}

/*
void FoodItems::update(const HttpRequestPtr &req,
                       std::function<void(const HttpResponsePtr &)> &&callback)
{

}*/

void FoodItems::deleteOne(const HttpRequestPtr &req,
                          std::function<void(const HttpResponsePtr &)> &&callback,
                          std::string &&id)
{
}
