/**
 *
 *  FoodItems.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "FoodItems.h"

#include <drogon/HttpTypes.h>
#include <json/value.h>
#include <trantor/utils/Logger.h>

#include <cstdlib>
#include <string>

// void FoodItems::getOne(const HttpRequestPtr& req, std::function<void(const HttpResponsePtr&)>&& callback,
//                        std::string&& id) {
//     char* errPtr;
//     int intId = std::strtol(id.c_str(), &errPtr, 10);
//     // if the id is negative the error pointer doesn't point to the end of the string
//     if (intId < 0 || *errPtr != '\0' || id.empty()) {
//         callback(HttpResponse::newHttpResponse(drogon::k400BadRequest, drogon::CT_TEXT_PLAIN));
//         return;
//     }
//     auto dbClient = app().getDbClient();
//     try {
//         auto result = dbClient->execSqlSync("SELECT * FROM food_items WHERE id = $1", id);
//         if (result.empty()) {
//             callback(HttpResponse::newHttpResponse(drogon::k400BadRequest, drogon::CT_TEXT_PLAIN));
//             return;
//         }
//         drogon::orm::Row row = result.front();
//         Json::Value menuInfo;
//         // set the values in the return json
//         for (const drogon::orm::Field& field : row) {
//             menuInfo[field.name()] = field.c_str();
//         }
//         callback(HttpResponse::newHttpJsonResponse(menuInfo));
//     } catch (std::exception& e) {
//         callback(HttpResponse::newHttpResponse(drogon::k500InternalServerError, drogon::CT_TEXT_PLAIN));
//     }
// }

// changed this to get while also accepting a restaurantId
void FoodItems::get(const HttpRequestPtr& req, std::function<void(const HttpResponsePtr&)>&& callback,
                    const std::string& restaurantId) {
    char* errPtr;
    int intId = std::strtol(restaurantId.c_str(), &errPtr, 10);
    // if the id is negative the error pointer doesn't point to the end of the string
    if (intId < 0 || *errPtr != '\0' || restaurantId.empty()) {
        LOG_INFO << "id is " << restaurantId;
        callback(HttpResponse::newHttpResponse(drogon::k400BadRequest, drogon::CT_TEXT_PLAIN));
        return;
    }
    auto dbClient = app().getDbClient();
    try {
        auto result = dbClient->execSqlSync(
            "SELECT * FROM food_items JOIN menus ON food_items.menu_id = menus.id WHERE restaurant_id = $1 ORDER "
            "BY menus.rating DESC",
            restaurantId);
        LOG_INFO << "the restaurantId is " << restaurantId;
        Json::Value totalFoodItems;
        // set the values in the return json
        int lastMenu = -1;
        Json::Value currMenu;
        for (const auto& row : result) {
            // separate each entry into its own menu
            if (lastMenu == -1) {
                lastMenu = row["menu_id"].as<int>();
            } else if (lastMenu != row["menu_id"].as<int>()) {
                totalFoodItems.append(Json::Value(currMenu));
                currMenu = Json::Value();
                lastMenu = row["menu_id"].as<int>();
            }
            Json::Value currItem;
            for (const drogon::orm::Field& field : row) {
                currItem[field.name()] = field.c_str();
            }
            currMenu.append(currItem);
        }
        if (!result.empty()) {
            // for the last menu
            totalFoodItems.append(Json::Value(currMenu));
        }
        // return json with all the food items in the menu
        LOG_INFO << "food items" << totalFoodItems.toStyledString();
        callback(HttpResponse::newHttpJsonResponse(totalFoodItems));
    } catch (std::exception& e) {
        callback(HttpResponse::newHttpResponse(drogon::k500InternalServerError, drogon::CT_TEXT_PLAIN));
    }
}

void FoodItems::create(const HttpRequestPtr& req, std::function<void(const HttpResponsePtr&)>&& callback) {
    Json::Value body;
    Json::Reader reader;
    reader.parse(req->getBody().data(), body, false);
    std::string menuId(body["menu_id"].asString());
    std::string dishName(body["dish_name"].asString());
    std::string menuSection(body["menu_section"].asString());
    std::string dishDesc(body["dish_description"].asString());
    std::string price(body["dish_price"].asString());
    char* errPtr;
    int intMenuId = std::strtol(menuId.c_str(), &errPtr, 10);
    // if the id is negative the error pointer doesn't point to the end of the string
    if (intMenuId < 0 || *errPtr != '\0' || menuId.empty()) {
        // menu id is wrong
        LOG_INFO << "menu id is wrong " << menuId;
        callback(HttpResponse::newHttpResponse(drogon::k400BadRequest, drogon::CT_TEXT_PLAIN));
        return;
    }
    double doublePrice = std::strtod(price.c_str(), &errPtr);
    if (doublePrice < 0 || *errPtr != '\0' || price.empty()) {
        // price is wrong
        LOG_INFO << "price is wrong " << price;
        callback(HttpResponse::newHttpResponse(drogon::k400BadRequest, drogon::CT_TEXT_PLAIN));
        return;
    }
    if (dishName.empty()) {
        // dish name (required) is empty
        LOG_INFO << "dish name is empty " << dishName;
        callback(HttpResponse::newHttpResponse(drogon::k400BadRequest, drogon::CT_TEXT_PLAIN));
        return;
    }
    auto dbClient = app().getDbClient();
    if (menuSection.empty()) {
        menuSection = "NULL";
    }
    if (dishDesc.empty()) {
        dishDesc = "NULL";
    }
    try {
        auto result = dbClient->execSqlSync(
            "INSERT INTO food_items (menu_id, dish_name, menu_section, dish_desc, price) VALUES ($1, $2, $3, $4, "
            "$5)",
            menuId, dishName, menuSection, dishDesc, price);
        callback(HttpResponse::newHttpResponse(drogon::k200OK, CT_TEXT_PLAIN));
    } catch (std::exception& e) {
        callback(HttpResponse::newHttpResponse(drogon::k500InternalServerError, drogon::CT_TEXT_PLAIN));
    }
}

void FoodItems::updateOne(const HttpRequestPtr& req, std::function<void(const HttpResponsePtr&)>&& callback,
                          std::string&& id) {
    // should check for the health value and ping ai api if it's 0, then update it, and give the user back a health
    // value
    callback(HttpResponse::newHttpResponse(drogon::k404NotFound, drogon::CT_TEXT_PLAIN));
}

/*
void FoodItems::update(const HttpRequestPtr &req,
                       std::function<void(const HttpResponsePtr &)> &&callback)
{

}*/

void FoodItems::deleteOne(const HttpRequestPtr& req, std::function<void(const HttpResponsePtr&)>&& callback,
                          std::string&& id) {
    // food items should be deleted via cascade
    callback(HttpResponse::newHttpResponse(drogon::k404NotFound, drogon::CT_TEXT_PLAIN));
}
