/**
 *
 *  Menu.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "Menu.h"

#include <drogon/HttpClient.h>
#include <drogon/HttpResponse.h>
#include <drogon/HttpTypes.h>
#include <drogon/utils/Utilities.h>
#include <json/value.h>
#include <json/writer.h>
#include <trantor/utils/Logger.h>

#include <string>

void Menu::getOne(const HttpRequestPtr& req, std::function<void(const HttpResponsePtr&)>&& callback,
                  std::string&& id) {
}

void Menu::get(const HttpRequestPtr& req, std::function<void(const HttpResponsePtr&)>&& callback) {
}
void Menu::create(const HttpRequestPtr& req, std::function<void(const HttpResponsePtr&)>&& callback) {
}
void Menu::updateOne(const HttpRequestPtr& req, std::function<void(const HttpResponsePtr&)>&& callback,
                     std::string&& id) {
}

/*
void Menu::update(const HttpRequestPtr &req,
                  std::function<void(const HttpResponsePtr &)> &&callback)
{

}*/

void Menu::deleteOne(const HttpRequestPtr& req, std::function<void(const HttpResponsePtr&)>&& callback,
                     std::string&& id) {
}
