/**
 *
 *  FoodPantries.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "FoodPantries.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::biteful;

const std::string FoodPantries::Cols::_id = "\"id\"";
const std::string FoodPantries::Cols::_agency = "\"agency\"";
const std::string FoodPantries::Cols::_day_of_week = "\"day_of_week\"";
const std::string FoodPantries::Cols::_open_time = "\"open_time\"";
const std::string FoodPantries::Cols::_close_time = "\"close_time\"";
const std::string FoodPantries::Cols::_address = "\"address\"";
const std::string FoodPantries::Cols::_latitude = "\"latitude\"";
const std::string FoodPantries::Cols::_longitude = "\"longitude\"";
const std::string FoodPantries::Cols::_meal_type = "\"meal_type\"";
const std::string FoodPantries::Cols::_frequency = "\"frequency\"";
const std::string FoodPantries::Cols::_phone = "\"phone\"";
const std::string FoodPantries::Cols::_program = "\"program\"";
const std::string FoodPantries::primaryKeyName = "id";
const bool FoodPantries::hasPrimaryKey = true;
const std::string FoodPantries::tableName = "\"food_pantries\"";

const std::vector<typename FoodPantries::MetaData> FoodPantries::metaData_={
{"id","int32_t","integer",4,1,1,1},
{"agency","std::string","text",0,0,0,1},
{"day_of_week","std::string","text",0,0,0,1},
{"open_time","std::string","time without time zone",0,0,0,0},
{"close_time","std::string","time without time zone",0,0,0,0},
{"address","std::string","text",0,0,0,0},
{"latitude","double","double precision",8,0,0,0},
{"longitude","double","double precision",8,0,0,0},
{"meal_type","std::string","text",0,0,0,0},
{"frequency","std::string","text",0,0,0,0},
{"phone","std::string","text",0,0,0,0},
{"program","std::string","text",0,0,0,0}
};
const std::string &FoodPantries::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
FoodPantries::FoodPantries(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int32_t>(r["id"].as<int32_t>());
        }
        if(!r["agency"].isNull())
        {
            agency_=std::make_shared<std::string>(r["agency"].as<std::string>());
        }
        if(!r["day_of_week"].isNull())
        {
            dayOfWeek_=std::make_shared<std::string>(r["day_of_week"].as<std::string>());
        }
        if(!r["open_time"].isNull())
        {
            openTime_=std::make_shared<std::string>(r["open_time"].as<std::string>());
        }
        if(!r["close_time"].isNull())
        {
            closeTime_=std::make_shared<std::string>(r["close_time"].as<std::string>());
        }
        if(!r["address"].isNull())
        {
            address_=std::make_shared<std::string>(r["address"].as<std::string>());
        }
        if(!r["latitude"].isNull())
        {
            latitude_=std::make_shared<double>(r["latitude"].as<double>());
        }
        if(!r["longitude"].isNull())
        {
            longitude_=std::make_shared<double>(r["longitude"].as<double>());
        }
        if(!r["meal_type"].isNull())
        {
            mealType_=std::make_shared<std::string>(r["meal_type"].as<std::string>());
        }
        if(!r["frequency"].isNull())
        {
            frequency_=std::make_shared<std::string>(r["frequency"].as<std::string>());
        }
        if(!r["phone"].isNull())
        {
            phone_=std::make_shared<std::string>(r["phone"].as<std::string>());
        }
        if(!r["program"].isNull())
        {
            program_=std::make_shared<std::string>(r["program"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 12 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            agency_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            dayOfWeek_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            openTime_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            closeTime_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            address_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            latitude_=std::make_shared<double>(r[index].as<double>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            longitude_=std::make_shared<double>(r[index].as<double>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            mealType_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            frequency_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 10;
        if(!r[index].isNull())
        {
            phone_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 11;
        if(!r[index].isNull())
        {
            program_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

FoodPantries::FoodPantries(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 12)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            agency_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            dayOfWeek_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            openTime_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            closeTime_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            address_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            latitude_=std::make_shared<double>(pJson[pMasqueradingVector[6]].asDouble());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            longitude_=std::make_shared<double>(pJson[pMasqueradingVector[7]].asDouble());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            mealType_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            frequency_=std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            phone_=std::make_shared<std::string>(pJson[pMasqueradingVector[10]].asString());
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            program_=std::make_shared<std::string>(pJson[pMasqueradingVector[11]].asString());
        }
    }
}

FoodPantries::FoodPantries(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("agency"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["agency"].isNull())
        {
            agency_=std::make_shared<std::string>(pJson["agency"].asString());
        }
    }
    if(pJson.isMember("day_of_week"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["day_of_week"].isNull())
        {
            dayOfWeek_=std::make_shared<std::string>(pJson["day_of_week"].asString());
        }
    }
    if(pJson.isMember("open_time"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["open_time"].isNull())
        {
            openTime_=std::make_shared<std::string>(pJson["open_time"].asString());
        }
    }
    if(pJson.isMember("close_time"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["close_time"].isNull())
        {
            closeTime_=std::make_shared<std::string>(pJson["close_time"].asString());
        }
    }
    if(pJson.isMember("address"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["address"].isNull())
        {
            address_=std::make_shared<std::string>(pJson["address"].asString());
        }
    }
    if(pJson.isMember("latitude"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["latitude"].isNull())
        {
            latitude_=std::make_shared<double>(pJson["latitude"].asDouble());
        }
    }
    if(pJson.isMember("longitude"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["longitude"].isNull())
        {
            longitude_=std::make_shared<double>(pJson["longitude"].asDouble());
        }
    }
    if(pJson.isMember("meal_type"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["meal_type"].isNull())
        {
            mealType_=std::make_shared<std::string>(pJson["meal_type"].asString());
        }
    }
    if(pJson.isMember("frequency"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["frequency"].isNull())
        {
            frequency_=std::make_shared<std::string>(pJson["frequency"].asString());
        }
    }
    if(pJson.isMember("phone"))
    {
        dirtyFlag_[10]=true;
        if(!pJson["phone"].isNull())
        {
            phone_=std::make_shared<std::string>(pJson["phone"].asString());
        }
    }
    if(pJson.isMember("program"))
    {
        dirtyFlag_[11]=true;
        if(!pJson["program"].isNull())
        {
            program_=std::make_shared<std::string>(pJson["program"].asString());
        }
    }
}

void FoodPantries::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 12)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            agency_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            dayOfWeek_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            openTime_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            closeTime_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            address_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            latitude_=std::make_shared<double>(pJson[pMasqueradingVector[6]].asDouble());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            longitude_=std::make_shared<double>(pJson[pMasqueradingVector[7]].asDouble());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            mealType_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            frequency_=std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            phone_=std::make_shared<std::string>(pJson[pMasqueradingVector[10]].asString());
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            program_=std::make_shared<std::string>(pJson[pMasqueradingVector[11]].asString());
        }
    }
}

void FoodPantries::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("agency"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["agency"].isNull())
        {
            agency_=std::make_shared<std::string>(pJson["agency"].asString());
        }
    }
    if(pJson.isMember("day_of_week"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["day_of_week"].isNull())
        {
            dayOfWeek_=std::make_shared<std::string>(pJson["day_of_week"].asString());
        }
    }
    if(pJson.isMember("open_time"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["open_time"].isNull())
        {
            openTime_=std::make_shared<std::string>(pJson["open_time"].asString());
        }
    }
    if(pJson.isMember("close_time"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["close_time"].isNull())
        {
            closeTime_=std::make_shared<std::string>(pJson["close_time"].asString());
        }
    }
    if(pJson.isMember("address"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["address"].isNull())
        {
            address_=std::make_shared<std::string>(pJson["address"].asString());
        }
    }
    if(pJson.isMember("latitude"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["latitude"].isNull())
        {
            latitude_=std::make_shared<double>(pJson["latitude"].asDouble());
        }
    }
    if(pJson.isMember("longitude"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["longitude"].isNull())
        {
            longitude_=std::make_shared<double>(pJson["longitude"].asDouble());
        }
    }
    if(pJson.isMember("meal_type"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["meal_type"].isNull())
        {
            mealType_=std::make_shared<std::string>(pJson["meal_type"].asString());
        }
    }
    if(pJson.isMember("frequency"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["frequency"].isNull())
        {
            frequency_=std::make_shared<std::string>(pJson["frequency"].asString());
        }
    }
    if(pJson.isMember("phone"))
    {
        dirtyFlag_[10] = true;
        if(!pJson["phone"].isNull())
        {
            phone_=std::make_shared<std::string>(pJson["phone"].asString());
        }
    }
    if(pJson.isMember("program"))
    {
        dirtyFlag_[11] = true;
        if(!pJson["program"].isNull())
        {
            program_=std::make_shared<std::string>(pJson["program"].asString());
        }
    }
}

const int32_t &FoodPantries::getValueOfId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &FoodPantries::getId() const noexcept
{
    return id_;
}
void FoodPantries::setId(const int32_t &pId) noexcept
{
    id_ = std::make_shared<int32_t>(pId);
    dirtyFlag_[0] = true;
}
const typename FoodPantries::PrimaryKeyType & FoodPantries::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &FoodPantries::getValueOfAgency() const noexcept
{
    static const std::string defaultValue = std::string();
    if(agency_)
        return *agency_;
    return defaultValue;
}
const std::shared_ptr<std::string> &FoodPantries::getAgency() const noexcept
{
    return agency_;
}
void FoodPantries::setAgency(const std::string &pAgency) noexcept
{
    agency_ = std::make_shared<std::string>(pAgency);
    dirtyFlag_[1] = true;
}
void FoodPantries::setAgency(std::string &&pAgency) noexcept
{
    agency_ = std::make_shared<std::string>(std::move(pAgency));
    dirtyFlag_[1] = true;
}

const std::string &FoodPantries::getValueOfDayOfWeek() const noexcept
{
    static const std::string defaultValue = std::string();
    if(dayOfWeek_)
        return *dayOfWeek_;
    return defaultValue;
}
const std::shared_ptr<std::string> &FoodPantries::getDayOfWeek() const noexcept
{
    return dayOfWeek_;
}
void FoodPantries::setDayOfWeek(const std::string &pDayOfWeek) noexcept
{
    dayOfWeek_ = std::make_shared<std::string>(pDayOfWeek);
    dirtyFlag_[2] = true;
}
void FoodPantries::setDayOfWeek(std::string &&pDayOfWeek) noexcept
{
    dayOfWeek_ = std::make_shared<std::string>(std::move(pDayOfWeek));
    dirtyFlag_[2] = true;
}

const std::string &FoodPantries::getValueOfOpenTime() const noexcept
{
    static const std::string defaultValue = std::string();
    if(openTime_)
        return *openTime_;
    return defaultValue;
}
const std::shared_ptr<std::string> &FoodPantries::getOpenTime() const noexcept
{
    return openTime_;
}
void FoodPantries::setOpenTime(const std::string &pOpenTime) noexcept
{
    openTime_ = std::make_shared<std::string>(pOpenTime);
    dirtyFlag_[3] = true;
}
void FoodPantries::setOpenTime(std::string &&pOpenTime) noexcept
{
    openTime_ = std::make_shared<std::string>(std::move(pOpenTime));
    dirtyFlag_[3] = true;
}
void FoodPantries::setOpenTimeToNull() noexcept
{
    openTime_.reset();
    dirtyFlag_[3] = true;
}

const std::string &FoodPantries::getValueOfCloseTime() const noexcept
{
    static const std::string defaultValue = std::string();
    if(closeTime_)
        return *closeTime_;
    return defaultValue;
}
const std::shared_ptr<std::string> &FoodPantries::getCloseTime() const noexcept
{
    return closeTime_;
}
void FoodPantries::setCloseTime(const std::string &pCloseTime) noexcept
{
    closeTime_ = std::make_shared<std::string>(pCloseTime);
    dirtyFlag_[4] = true;
}
void FoodPantries::setCloseTime(std::string &&pCloseTime) noexcept
{
    closeTime_ = std::make_shared<std::string>(std::move(pCloseTime));
    dirtyFlag_[4] = true;
}
void FoodPantries::setCloseTimeToNull() noexcept
{
    closeTime_.reset();
    dirtyFlag_[4] = true;
}

const std::string &FoodPantries::getValueOfAddress() const noexcept
{
    static const std::string defaultValue = std::string();
    if(address_)
        return *address_;
    return defaultValue;
}
const std::shared_ptr<std::string> &FoodPantries::getAddress() const noexcept
{
    return address_;
}
void FoodPantries::setAddress(const std::string &pAddress) noexcept
{
    address_ = std::make_shared<std::string>(pAddress);
    dirtyFlag_[5] = true;
}
void FoodPantries::setAddress(std::string &&pAddress) noexcept
{
    address_ = std::make_shared<std::string>(std::move(pAddress));
    dirtyFlag_[5] = true;
}
void FoodPantries::setAddressToNull() noexcept
{
    address_.reset();
    dirtyFlag_[5] = true;
}

const double &FoodPantries::getValueOfLatitude() const noexcept
{
    static const double defaultValue = double();
    if(latitude_)
        return *latitude_;
    return defaultValue;
}
const std::shared_ptr<double> &FoodPantries::getLatitude() const noexcept
{
    return latitude_;
}
void FoodPantries::setLatitude(const double &pLatitude) noexcept
{
    latitude_ = std::make_shared<double>(pLatitude);
    dirtyFlag_[6] = true;
}
void FoodPantries::setLatitudeToNull() noexcept
{
    latitude_.reset();
    dirtyFlag_[6] = true;
}

const double &FoodPantries::getValueOfLongitude() const noexcept
{
    static const double defaultValue = double();
    if(longitude_)
        return *longitude_;
    return defaultValue;
}
const std::shared_ptr<double> &FoodPantries::getLongitude() const noexcept
{
    return longitude_;
}
void FoodPantries::setLongitude(const double &pLongitude) noexcept
{
    longitude_ = std::make_shared<double>(pLongitude);
    dirtyFlag_[7] = true;
}
void FoodPantries::setLongitudeToNull() noexcept
{
    longitude_.reset();
    dirtyFlag_[7] = true;
}

const std::string &FoodPantries::getValueOfMealType() const noexcept
{
    static const std::string defaultValue = std::string();
    if(mealType_)
        return *mealType_;
    return defaultValue;
}
const std::shared_ptr<std::string> &FoodPantries::getMealType() const noexcept
{
    return mealType_;
}
void FoodPantries::setMealType(const std::string &pMealType) noexcept
{
    mealType_ = std::make_shared<std::string>(pMealType);
    dirtyFlag_[8] = true;
}
void FoodPantries::setMealType(std::string &&pMealType) noexcept
{
    mealType_ = std::make_shared<std::string>(std::move(pMealType));
    dirtyFlag_[8] = true;
}
void FoodPantries::setMealTypeToNull() noexcept
{
    mealType_.reset();
    dirtyFlag_[8] = true;
}

const std::string &FoodPantries::getValueOfFrequency() const noexcept
{
    static const std::string defaultValue = std::string();
    if(frequency_)
        return *frequency_;
    return defaultValue;
}
const std::shared_ptr<std::string> &FoodPantries::getFrequency() const noexcept
{
    return frequency_;
}
void FoodPantries::setFrequency(const std::string &pFrequency) noexcept
{
    frequency_ = std::make_shared<std::string>(pFrequency);
    dirtyFlag_[9] = true;
}
void FoodPantries::setFrequency(std::string &&pFrequency) noexcept
{
    frequency_ = std::make_shared<std::string>(std::move(pFrequency));
    dirtyFlag_[9] = true;
}
void FoodPantries::setFrequencyToNull() noexcept
{
    frequency_.reset();
    dirtyFlag_[9] = true;
}

const std::string &FoodPantries::getValueOfPhone() const noexcept
{
    static const std::string defaultValue = std::string();
    if(phone_)
        return *phone_;
    return defaultValue;
}
const std::shared_ptr<std::string> &FoodPantries::getPhone() const noexcept
{
    return phone_;
}
void FoodPantries::setPhone(const std::string &pPhone) noexcept
{
    phone_ = std::make_shared<std::string>(pPhone);
    dirtyFlag_[10] = true;
}
void FoodPantries::setPhone(std::string &&pPhone) noexcept
{
    phone_ = std::make_shared<std::string>(std::move(pPhone));
    dirtyFlag_[10] = true;
}
void FoodPantries::setPhoneToNull() noexcept
{
    phone_.reset();
    dirtyFlag_[10] = true;
}

const std::string &FoodPantries::getValueOfProgram() const noexcept
{
    static const std::string defaultValue = std::string();
    if(program_)
        return *program_;
    return defaultValue;
}
const std::shared_ptr<std::string> &FoodPantries::getProgram() const noexcept
{
    return program_;
}
void FoodPantries::setProgram(const std::string &pProgram) noexcept
{
    program_ = std::make_shared<std::string>(pProgram);
    dirtyFlag_[11] = true;
}
void FoodPantries::setProgram(std::string &&pProgram) noexcept
{
    program_ = std::make_shared<std::string>(std::move(pProgram));
    dirtyFlag_[11] = true;
}
void FoodPantries::setProgramToNull() noexcept
{
    program_.reset();
    dirtyFlag_[11] = true;
}

void FoodPantries::updateId(const uint64_t id)
{
}

const std::vector<std::string> &FoodPantries::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "agency",
        "day_of_week",
        "open_time",
        "close_time",
        "address",
        "latitude",
        "longitude",
        "meal_type",
        "frequency",
        "phone",
        "program"
    };
    return inCols;
}

void FoodPantries::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getAgency())
        {
            binder << getValueOfAgency();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getDayOfWeek())
        {
            binder << getValueOfDayOfWeek();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getOpenTime())
        {
            binder << getValueOfOpenTime();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getCloseTime())
        {
            binder << getValueOfCloseTime();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getAddress())
        {
            binder << getValueOfAddress();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getLatitude())
        {
            binder << getValueOfLatitude();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getLongitude())
        {
            binder << getValueOfLongitude();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getMealType())
        {
            binder << getValueOfMealType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getFrequency())
        {
            binder << getValueOfFrequency();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getPhone())
        {
            binder << getValueOfPhone();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getProgram())
        {
            binder << getValueOfProgram();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> FoodPantries::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    if(dirtyFlag_[10])
    {
        ret.push_back(getColumnName(10));
    }
    if(dirtyFlag_[11])
    {
        ret.push_back(getColumnName(11));
    }
    return ret;
}

void FoodPantries::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getAgency())
        {
            binder << getValueOfAgency();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getDayOfWeek())
        {
            binder << getValueOfDayOfWeek();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getOpenTime())
        {
            binder << getValueOfOpenTime();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getCloseTime())
        {
            binder << getValueOfCloseTime();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getAddress())
        {
            binder << getValueOfAddress();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getLatitude())
        {
            binder << getValueOfLatitude();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getLongitude())
        {
            binder << getValueOfLongitude();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getMealType())
        {
            binder << getValueOfMealType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getFrequency())
        {
            binder << getValueOfFrequency();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getPhone())
        {
            binder << getValueOfPhone();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getProgram())
        {
            binder << getValueOfProgram();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value FoodPantries::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getAgency())
    {
        ret["agency"]=getValueOfAgency();
    }
    else
    {
        ret["agency"]=Json::Value();
    }
    if(getDayOfWeek())
    {
        ret["day_of_week"]=getValueOfDayOfWeek();
    }
    else
    {
        ret["day_of_week"]=Json::Value();
    }
    if(getOpenTime())
    {
        ret["open_time"]=getValueOfOpenTime();
    }
    else
    {
        ret["open_time"]=Json::Value();
    }
    if(getCloseTime())
    {
        ret["close_time"]=getValueOfCloseTime();
    }
    else
    {
        ret["close_time"]=Json::Value();
    }
    if(getAddress())
    {
        ret["address"]=getValueOfAddress();
    }
    else
    {
        ret["address"]=Json::Value();
    }
    if(getLatitude())
    {
        ret["latitude"]=getValueOfLatitude();
    }
    else
    {
        ret["latitude"]=Json::Value();
    }
    if(getLongitude())
    {
        ret["longitude"]=getValueOfLongitude();
    }
    else
    {
        ret["longitude"]=Json::Value();
    }
    if(getMealType())
    {
        ret["meal_type"]=getValueOfMealType();
    }
    else
    {
        ret["meal_type"]=Json::Value();
    }
    if(getFrequency())
    {
        ret["frequency"]=getValueOfFrequency();
    }
    else
    {
        ret["frequency"]=Json::Value();
    }
    if(getPhone())
    {
        ret["phone"]=getValueOfPhone();
    }
    else
    {
        ret["phone"]=Json::Value();
    }
    if(getProgram())
    {
        ret["program"]=getValueOfProgram();
    }
    else
    {
        ret["program"]=Json::Value();
    }
    return ret;
}

Json::Value FoodPantries::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 12)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getAgency())
            {
                ret[pMasqueradingVector[1]]=getValueOfAgency();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getDayOfWeek())
            {
                ret[pMasqueradingVector[2]]=getValueOfDayOfWeek();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getOpenTime())
            {
                ret[pMasqueradingVector[3]]=getValueOfOpenTime();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getCloseTime())
            {
                ret[pMasqueradingVector[4]]=getValueOfCloseTime();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getAddress())
            {
                ret[pMasqueradingVector[5]]=getValueOfAddress();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getLatitude())
            {
                ret[pMasqueradingVector[6]]=getValueOfLatitude();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getLongitude())
            {
                ret[pMasqueradingVector[7]]=getValueOfLongitude();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getMealType())
            {
                ret[pMasqueradingVector[8]]=getValueOfMealType();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getFrequency())
            {
                ret[pMasqueradingVector[9]]=getValueOfFrequency();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[10].empty())
        {
            if(getPhone())
            {
                ret[pMasqueradingVector[10]]=getValueOfPhone();
            }
            else
            {
                ret[pMasqueradingVector[10]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[11].empty())
        {
            if(getProgram())
            {
                ret[pMasqueradingVector[11]]=getValueOfProgram();
            }
            else
            {
                ret[pMasqueradingVector[11]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getAgency())
    {
        ret["agency"]=getValueOfAgency();
    }
    else
    {
        ret["agency"]=Json::Value();
    }
    if(getDayOfWeek())
    {
        ret["day_of_week"]=getValueOfDayOfWeek();
    }
    else
    {
        ret["day_of_week"]=Json::Value();
    }
    if(getOpenTime())
    {
        ret["open_time"]=getValueOfOpenTime();
    }
    else
    {
        ret["open_time"]=Json::Value();
    }
    if(getCloseTime())
    {
        ret["close_time"]=getValueOfCloseTime();
    }
    else
    {
        ret["close_time"]=Json::Value();
    }
    if(getAddress())
    {
        ret["address"]=getValueOfAddress();
    }
    else
    {
        ret["address"]=Json::Value();
    }
    if(getLatitude())
    {
        ret["latitude"]=getValueOfLatitude();
    }
    else
    {
        ret["latitude"]=Json::Value();
    }
    if(getLongitude())
    {
        ret["longitude"]=getValueOfLongitude();
    }
    else
    {
        ret["longitude"]=Json::Value();
    }
    if(getMealType())
    {
        ret["meal_type"]=getValueOfMealType();
    }
    else
    {
        ret["meal_type"]=Json::Value();
    }
    if(getFrequency())
    {
        ret["frequency"]=getValueOfFrequency();
    }
    else
    {
        ret["frequency"]=Json::Value();
    }
    if(getPhone())
    {
        ret["phone"]=getValueOfPhone();
    }
    else
    {
        ret["phone"]=Json::Value();
    }
    if(getProgram())
    {
        ret["program"]=getValueOfProgram();
    }
    else
    {
        ret["program"]=Json::Value();
    }
    return ret;
}

bool FoodPantries::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("agency"))
    {
        if(!validJsonOfField(1, "agency", pJson["agency"], err, true))
            return false;
    }
    else
    {
        err="The agency column cannot be null";
        return false;
    }
    if(pJson.isMember("day_of_week"))
    {
        if(!validJsonOfField(2, "day_of_week", pJson["day_of_week"], err, true))
            return false;
    }
    else
    {
        err="The day_of_week column cannot be null";
        return false;
    }
    if(pJson.isMember("open_time"))
    {
        if(!validJsonOfField(3, "open_time", pJson["open_time"], err, true))
            return false;
    }
    if(pJson.isMember("close_time"))
    {
        if(!validJsonOfField(4, "close_time", pJson["close_time"], err, true))
            return false;
    }
    if(pJson.isMember("address"))
    {
        if(!validJsonOfField(5, "address", pJson["address"], err, true))
            return false;
    }
    if(pJson.isMember("latitude"))
    {
        if(!validJsonOfField(6, "latitude", pJson["latitude"], err, true))
            return false;
    }
    if(pJson.isMember("longitude"))
    {
        if(!validJsonOfField(7, "longitude", pJson["longitude"], err, true))
            return false;
    }
    if(pJson.isMember("meal_type"))
    {
        if(!validJsonOfField(8, "meal_type", pJson["meal_type"], err, true))
            return false;
    }
    if(pJson.isMember("frequency"))
    {
        if(!validJsonOfField(9, "frequency", pJson["frequency"], err, true))
            return false;
    }
    if(pJson.isMember("phone"))
    {
        if(!validJsonOfField(10, "phone", pJson["phone"], err, true))
            return false;
    }
    if(pJson.isMember("program"))
    {
        if(!validJsonOfField(11, "program", pJson["program"], err, true))
            return false;
    }
    return true;
}
bool FoodPantries::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                      const std::vector<std::string> &pMasqueradingVector,
                                                      std::string &err)
{
    if(pMasqueradingVector.size() != 12)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[10].empty())
      {
          if(pJson.isMember(pMasqueradingVector[10]))
          {
              if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[11].empty())
      {
          if(pJson.isMember(pMasqueradingVector[11]))
          {
              if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool FoodPantries::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("agency"))
    {
        if(!validJsonOfField(1, "agency", pJson["agency"], err, false))
            return false;
    }
    if(pJson.isMember("day_of_week"))
    {
        if(!validJsonOfField(2, "day_of_week", pJson["day_of_week"], err, false))
            return false;
    }
    if(pJson.isMember("open_time"))
    {
        if(!validJsonOfField(3, "open_time", pJson["open_time"], err, false))
            return false;
    }
    if(pJson.isMember("close_time"))
    {
        if(!validJsonOfField(4, "close_time", pJson["close_time"], err, false))
            return false;
    }
    if(pJson.isMember("address"))
    {
        if(!validJsonOfField(5, "address", pJson["address"], err, false))
            return false;
    }
    if(pJson.isMember("latitude"))
    {
        if(!validJsonOfField(6, "latitude", pJson["latitude"], err, false))
            return false;
    }
    if(pJson.isMember("longitude"))
    {
        if(!validJsonOfField(7, "longitude", pJson["longitude"], err, false))
            return false;
    }
    if(pJson.isMember("meal_type"))
    {
        if(!validJsonOfField(8, "meal_type", pJson["meal_type"], err, false))
            return false;
    }
    if(pJson.isMember("frequency"))
    {
        if(!validJsonOfField(9, "frequency", pJson["frequency"], err, false))
            return false;
    }
    if(pJson.isMember("phone"))
    {
        if(!validJsonOfField(10, "phone", pJson["phone"], err, false))
            return false;
    }
    if(pJson.isMember("program"))
    {
        if(!validJsonOfField(11, "program", pJson["program"], err, false))
            return false;
    }
    return true;
}
bool FoodPantries::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                    const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err)
{
    if(pMasqueradingVector.size() != 12)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
      if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
      {
          if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, false))
              return false;
      }
      if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
      {
          if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool FoodPantries::validJsonOfField(size_t index,
                                    const std::string &fieldName,
                                    const Json::Value &pJson,
                                    std::string &err,
                                    bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isNumeric())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isNumeric())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 9:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 10:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 11:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
