/**
 *
 *  FoodPantries.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "FoodPantries.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::biteful;

const std::string FoodPantries::Cols::_id = "\"id\"";
const std::string FoodPantries::Cols::_agency = "\"agency\"";
const std::string FoodPantries::Cols::_day_of_week = "\"day_of_week\"";
const std::string FoodPantries::Cols::_open_time = "\"open_time\"";
const std::string FoodPantries::Cols::_close_time = "\"close_time\"";
const std::string FoodPantries::Cols::_street = "\"street\"";
const std::string FoodPantries::Cols::_building = "\"building\"";
const std::string FoodPantries::Cols::_boro = "\"boro\"";
const std::string FoodPantries::Cols::_zipcode = "\"zipcode\"";
const std::string FoodPantries::Cols::_latitude = "\"latitude\"";
const std::string FoodPantries::Cols::_longitude = "\"longitude\"";
const std::string FoodPantries::Cols::_meal_type = "\"meal_type\"";
const std::string FoodPantries::Cols::_frequency = "\"frequency\"";
const std::string FoodPantries::Cols::_phone = "\"phone\"";
const std::string FoodPantries::Cols::_program = "\"program\"";
const std::string FoodPantries::primaryKeyName = "id";
const bool FoodPantries::hasPrimaryKey = true;
const std::string FoodPantries::tableName = "\"food_pantries\"";

const std::vector<typename FoodPantries::MetaData> FoodPantries::metaData_={
{"id","int32_t","integer",4,1,1,1},
{"agency","std::string","text",0,0,0,1},
{"day_of_week","std::string","text",0,0,0,1},
{"open_time","std::string","time without time zone",0,0,0,0},
{"close_time","std::string","time without time zone",0,0,0,0},
{"street","std::string","text",0,0,0,0},
{"building","std::string","text",0,0,0,0},
{"boro","std::string","text",0,0,0,0},
{"zipcode","std::string","text",0,0,0,0},
{"latitude","double","double precision",8,0,0,0},
{"longitude","double","double precision",8,0,0,0},
{"meal_type","std::string","text",0,0,0,0},
{"frequency","std::string","text",0,0,0,0},
{"phone","std::string","text",0,0,0,0},
{"program","std::string","text",0,0,0,0}
};
const std::string &FoodPantries::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
FoodPantries::FoodPantries(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int32_t>(r["id"].as<int32_t>());
        }
        if(!r["agency"].isNull())
        {
            agency_=std::make_shared<std::string>(r["agency"].as<std::string>());
        }
        if(!r["day_of_week"].isNull())
        {
            dayOfWeek_=std::make_shared<std::string>(r["day_of_week"].as<std::string>());
        }
        if(!r["open_time"].isNull())
        {
            openTime_=std::make_shared<std::string>(r["open_time"].as<std::string>());
        }
        if(!r["close_time"].isNull())
        {
            closeTime_=std::make_shared<std::string>(r["close_time"].as<std::string>());
        }
        if(!r["street"].isNull())
        {
            street_=std::make_shared<std::string>(r["street"].as<std::string>());
        }
        if(!r["building"].isNull())
        {
            building_=std::make_shared<std::string>(r["building"].as<std::string>());
        }
        if(!r["boro"].isNull())
        {
            boro_=std::make_shared<std::string>(r["boro"].as<std::string>());
        }
        if(!r["zipcode"].isNull())
        {
            zipcode_=std::make_shared<std::string>(r["zipcode"].as<std::string>());
        }
        if(!r["latitude"].isNull())
        {
            latitude_=std::make_shared<double>(r["latitude"].as<double>());
        }
        if(!r["longitude"].isNull())
        {
            longitude_=std::make_shared<double>(r["longitude"].as<double>());
        }
        if(!r["meal_type"].isNull())
        {
            mealType_=std::make_shared<std::string>(r["meal_type"].as<std::string>());
        }
        if(!r["frequency"].isNull())
        {
            frequency_=std::make_shared<std::string>(r["frequency"].as<std::string>());
        }
        if(!r["phone"].isNull())
        {
            phone_=std::make_shared<std::string>(r["phone"].as<std::string>());
        }
        if(!r["program"].isNull())
        {
            program_=std::make_shared<std::string>(r["program"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 15 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            agency_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            dayOfWeek_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            openTime_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            closeTime_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            street_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            building_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            boro_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            zipcode_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            latitude_=std::make_shared<double>(r[index].as<double>());
        }
        index = offset + 10;
        if(!r[index].isNull())
        {
            longitude_=std::make_shared<double>(r[index].as<double>());
        }
        index = offset + 11;
        if(!r[index].isNull())
        {
            mealType_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 12;
        if(!r[index].isNull())
        {
            frequency_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 13;
        if(!r[index].isNull())
        {
            phone_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 14;
        if(!r[index].isNull())
        {
            program_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

FoodPantries::FoodPantries(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 15)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            agency_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            dayOfWeek_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            openTime_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            closeTime_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            street_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            building_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            boro_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            zipcode_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            latitude_=std::make_shared<double>(pJson[pMasqueradingVector[9]].asDouble());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            longitude_=std::make_shared<double>(pJson[pMasqueradingVector[10]].asDouble());
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            mealType_=std::make_shared<std::string>(pJson[pMasqueradingVector[11]].asString());
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            frequency_=std::make_shared<std::string>(pJson[pMasqueradingVector[12]].asString());
        }
    }
    if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
    {
        dirtyFlag_[13] = true;
        if(!pJson[pMasqueradingVector[13]].isNull())
        {
            phone_=std::make_shared<std::string>(pJson[pMasqueradingVector[13]].asString());
        }
    }
    if(!pMasqueradingVector[14].empty() && pJson.isMember(pMasqueradingVector[14]))
    {
        dirtyFlag_[14] = true;
        if(!pJson[pMasqueradingVector[14]].isNull())
        {
            program_=std::make_shared<std::string>(pJson[pMasqueradingVector[14]].asString());
        }
    }
}

FoodPantries::FoodPantries(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("agency"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["agency"].isNull())
        {
            agency_=std::make_shared<std::string>(pJson["agency"].asString());
        }
    }
    if(pJson.isMember("day_of_week"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["day_of_week"].isNull())
        {
            dayOfWeek_=std::make_shared<std::string>(pJson["day_of_week"].asString());
        }
    }
    if(pJson.isMember("open_time"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["open_time"].isNull())
        {
            openTime_=std::make_shared<std::string>(pJson["open_time"].asString());
        }
    }
    if(pJson.isMember("close_time"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["close_time"].isNull())
        {
            closeTime_=std::make_shared<std::string>(pJson["close_time"].asString());
        }
    }
    if(pJson.isMember("street"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["street"].isNull())
        {
            street_=std::make_shared<std::string>(pJson["street"].asString());
        }
    }
    if(pJson.isMember("building"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["building"].isNull())
        {
            building_=std::make_shared<std::string>(pJson["building"].asString());
        }
    }
    if(pJson.isMember("boro"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["boro"].isNull())
        {
            boro_=std::make_shared<std::string>(pJson["boro"].asString());
        }
    }
    if(pJson.isMember("zipcode"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["zipcode"].isNull())
        {
            zipcode_=std::make_shared<std::string>(pJson["zipcode"].asString());
        }
    }
    if(pJson.isMember("latitude"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["latitude"].isNull())
        {
            latitude_=std::make_shared<double>(pJson["latitude"].asDouble());
        }
    }
    if(pJson.isMember("longitude"))
    {
        dirtyFlag_[10]=true;
        if(!pJson["longitude"].isNull())
        {
            longitude_=std::make_shared<double>(pJson["longitude"].asDouble());
        }
    }
    if(pJson.isMember("meal_type"))
    {
        dirtyFlag_[11]=true;
        if(!pJson["meal_type"].isNull())
        {
            mealType_=std::make_shared<std::string>(pJson["meal_type"].asString());
        }
    }
    if(pJson.isMember("frequency"))
    {
        dirtyFlag_[12]=true;
        if(!pJson["frequency"].isNull())
        {
            frequency_=std::make_shared<std::string>(pJson["frequency"].asString());
        }
    }
    if(pJson.isMember("phone"))
    {
        dirtyFlag_[13]=true;
        if(!pJson["phone"].isNull())
        {
            phone_=std::make_shared<std::string>(pJson["phone"].asString());
        }
    }
    if(pJson.isMember("program"))
    {
        dirtyFlag_[14]=true;
        if(!pJson["program"].isNull())
        {
            program_=std::make_shared<std::string>(pJson["program"].asString());
        }
    }
}

void FoodPantries::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 15)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            agency_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            dayOfWeek_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            openTime_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            closeTime_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            street_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            building_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            boro_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            zipcode_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            latitude_=std::make_shared<double>(pJson[pMasqueradingVector[9]].asDouble());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            longitude_=std::make_shared<double>(pJson[pMasqueradingVector[10]].asDouble());
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            mealType_=std::make_shared<std::string>(pJson[pMasqueradingVector[11]].asString());
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            frequency_=std::make_shared<std::string>(pJson[pMasqueradingVector[12]].asString());
        }
    }
    if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
    {
        dirtyFlag_[13] = true;
        if(!pJson[pMasqueradingVector[13]].isNull())
        {
            phone_=std::make_shared<std::string>(pJson[pMasqueradingVector[13]].asString());
        }
    }
    if(!pMasqueradingVector[14].empty() && pJson.isMember(pMasqueradingVector[14]))
    {
        dirtyFlag_[14] = true;
        if(!pJson[pMasqueradingVector[14]].isNull())
        {
            program_=std::make_shared<std::string>(pJson[pMasqueradingVector[14]].asString());
        }
    }
}

void FoodPantries::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("agency"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["agency"].isNull())
        {
            agency_=std::make_shared<std::string>(pJson["agency"].asString());
        }
    }
    if(pJson.isMember("day_of_week"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["day_of_week"].isNull())
        {
            dayOfWeek_=std::make_shared<std::string>(pJson["day_of_week"].asString());
        }
    }
    if(pJson.isMember("open_time"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["open_time"].isNull())
        {
            openTime_=std::make_shared<std::string>(pJson["open_time"].asString());
        }
    }
    if(pJson.isMember("close_time"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["close_time"].isNull())
        {
            closeTime_=std::make_shared<std::string>(pJson["close_time"].asString());
        }
    }
    if(pJson.isMember("street"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["street"].isNull())
        {
            street_=std::make_shared<std::string>(pJson["street"].asString());
        }
    }
    if(pJson.isMember("building"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["building"].isNull())
        {
            building_=std::make_shared<std::string>(pJson["building"].asString());
        }
    }
    if(pJson.isMember("boro"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["boro"].isNull())
        {
            boro_=std::make_shared<std::string>(pJson["boro"].asString());
        }
    }
    if(pJson.isMember("zipcode"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["zipcode"].isNull())
        {
            zipcode_=std::make_shared<std::string>(pJson["zipcode"].asString());
        }
    }
    if(pJson.isMember("latitude"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["latitude"].isNull())
        {
            latitude_=std::make_shared<double>(pJson["latitude"].asDouble());
        }
    }
    if(pJson.isMember("longitude"))
    {
        dirtyFlag_[10] = true;
        if(!pJson["longitude"].isNull())
        {
            longitude_=std::make_shared<double>(pJson["longitude"].asDouble());
        }
    }
    if(pJson.isMember("meal_type"))
    {
        dirtyFlag_[11] = true;
        if(!pJson["meal_type"].isNull())
        {
            mealType_=std::make_shared<std::string>(pJson["meal_type"].asString());
        }
    }
    if(pJson.isMember("frequency"))
    {
        dirtyFlag_[12] = true;
        if(!pJson["frequency"].isNull())
        {
            frequency_=std::make_shared<std::string>(pJson["frequency"].asString());
        }
    }
    if(pJson.isMember("phone"))
    {
        dirtyFlag_[13] = true;
        if(!pJson["phone"].isNull())
        {
            phone_=std::make_shared<std::string>(pJson["phone"].asString());
        }
    }
    if(pJson.isMember("program"))
    {
        dirtyFlag_[14] = true;
        if(!pJson["program"].isNull())
        {
            program_=std::make_shared<std::string>(pJson["program"].asString());
        }
    }
}

const int32_t &FoodPantries::getValueOfId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &FoodPantries::getId() const noexcept
{
    return id_;
}
void FoodPantries::setId(const int32_t &pId) noexcept
{
    id_ = std::make_shared<int32_t>(pId);
    dirtyFlag_[0] = true;
}
const typename FoodPantries::PrimaryKeyType & FoodPantries::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &FoodPantries::getValueOfAgency() const noexcept
{
    static const std::string defaultValue = std::string();
    if(agency_)
        return *agency_;
    return defaultValue;
}
const std::shared_ptr<std::string> &FoodPantries::getAgency() const noexcept
{
    return agency_;
}
void FoodPantries::setAgency(const std::string &pAgency) noexcept
{
    agency_ = std::make_shared<std::string>(pAgency);
    dirtyFlag_[1] = true;
}
void FoodPantries::setAgency(std::string &&pAgency) noexcept
{
    agency_ = std::make_shared<std::string>(std::move(pAgency));
    dirtyFlag_[1] = true;
}

const std::string &FoodPantries::getValueOfDayOfWeek() const noexcept
{
    static const std::string defaultValue = std::string();
    if(dayOfWeek_)
        return *dayOfWeek_;
    return defaultValue;
}
const std::shared_ptr<std::string> &FoodPantries::getDayOfWeek() const noexcept
{
    return dayOfWeek_;
}
void FoodPantries::setDayOfWeek(const std::string &pDayOfWeek) noexcept
{
    dayOfWeek_ = std::make_shared<std::string>(pDayOfWeek);
    dirtyFlag_[2] = true;
}
void FoodPantries::setDayOfWeek(std::string &&pDayOfWeek) noexcept
{
    dayOfWeek_ = std::make_shared<std::string>(std::move(pDayOfWeek));
    dirtyFlag_[2] = true;
}

const std::string &FoodPantries::getValueOfOpenTime() const noexcept
{
    static const std::string defaultValue = std::string();
    if(openTime_)
        return *openTime_;
    return defaultValue;
}
const std::shared_ptr<std::string> &FoodPantries::getOpenTime() const noexcept
{
    return openTime_;
}
void FoodPantries::setOpenTime(const std::string &pOpenTime) noexcept
{
    openTime_ = std::make_shared<std::string>(pOpenTime);
    dirtyFlag_[3] = true;
}
void FoodPantries::setOpenTime(std::string &&pOpenTime) noexcept
{
    openTime_ = std::make_shared<std::string>(std::move(pOpenTime));
    dirtyFlag_[3] = true;
}
void FoodPantries::setOpenTimeToNull() noexcept
{
    openTime_.reset();
    dirtyFlag_[3] = true;
}

const std::string &FoodPantries::getValueOfCloseTime() const noexcept
{
    static const std::string defaultValue = std::string();
    if(closeTime_)
        return *closeTime_;
    return defaultValue;
}
const std::shared_ptr<std::string> &FoodPantries::getCloseTime() const noexcept
{
    return closeTime_;
}
void FoodPantries::setCloseTime(const std::string &pCloseTime) noexcept
{
    closeTime_ = std::make_shared<std::string>(pCloseTime);
    dirtyFlag_[4] = true;
}
void FoodPantries::setCloseTime(std::string &&pCloseTime) noexcept
{
    closeTime_ = std::make_shared<std::string>(std::move(pCloseTime));
    dirtyFlag_[4] = true;
}
void FoodPantries::setCloseTimeToNull() noexcept
{
    closeTime_.reset();
    dirtyFlag_[4] = true;
}

const std::string &FoodPantries::getValueOfStreet() const noexcept
{
    static const std::string defaultValue = std::string();
    if(street_)
        return *street_;
    return defaultValue;
}
const std::shared_ptr<std::string> &FoodPantries::getStreet() const noexcept
{
    return street_;
}
void FoodPantries::setStreet(const std::string &pStreet) noexcept
{
    street_ = std::make_shared<std::string>(pStreet);
    dirtyFlag_[5] = true;
}
void FoodPantries::setStreet(std::string &&pStreet) noexcept
{
    street_ = std::make_shared<std::string>(std::move(pStreet));
    dirtyFlag_[5] = true;
}
void FoodPantries::setStreetToNull() noexcept
{
    street_.reset();
    dirtyFlag_[5] = true;
}

const std::string &FoodPantries::getValueOfBuilding() const noexcept
{
    static const std::string defaultValue = std::string();
    if(building_)
        return *building_;
    return defaultValue;
}
const std::shared_ptr<std::string> &FoodPantries::getBuilding() const noexcept
{
    return building_;
}
void FoodPantries::setBuilding(const std::string &pBuilding) noexcept
{
    building_ = std::make_shared<std::string>(pBuilding);
    dirtyFlag_[6] = true;
}
void FoodPantries::setBuilding(std::string &&pBuilding) noexcept
{
    building_ = std::make_shared<std::string>(std::move(pBuilding));
    dirtyFlag_[6] = true;
}
void FoodPantries::setBuildingToNull() noexcept
{
    building_.reset();
    dirtyFlag_[6] = true;
}

const std::string &FoodPantries::getValueOfBoro() const noexcept
{
    static const std::string defaultValue = std::string();
    if(boro_)
        return *boro_;
    return defaultValue;
}
const std::shared_ptr<std::string> &FoodPantries::getBoro() const noexcept
{
    return boro_;
}
void FoodPantries::setBoro(const std::string &pBoro) noexcept
{
    boro_ = std::make_shared<std::string>(pBoro);
    dirtyFlag_[7] = true;
}
void FoodPantries::setBoro(std::string &&pBoro) noexcept
{
    boro_ = std::make_shared<std::string>(std::move(pBoro));
    dirtyFlag_[7] = true;
}
void FoodPantries::setBoroToNull() noexcept
{
    boro_.reset();
    dirtyFlag_[7] = true;
}

const std::string &FoodPantries::getValueOfZipcode() const noexcept
{
    static const std::string defaultValue = std::string();
    if(zipcode_)
        return *zipcode_;
    return defaultValue;
}
const std::shared_ptr<std::string> &FoodPantries::getZipcode() const noexcept
{
    return zipcode_;
}
void FoodPantries::setZipcode(const std::string &pZipcode) noexcept
{
    zipcode_ = std::make_shared<std::string>(pZipcode);
    dirtyFlag_[8] = true;
}
void FoodPantries::setZipcode(std::string &&pZipcode) noexcept
{
    zipcode_ = std::make_shared<std::string>(std::move(pZipcode));
    dirtyFlag_[8] = true;
}
void FoodPantries::setZipcodeToNull() noexcept
{
    zipcode_.reset();
    dirtyFlag_[8] = true;
}

const double &FoodPantries::getValueOfLatitude() const noexcept
{
    static const double defaultValue = double();
    if(latitude_)
        return *latitude_;
    return defaultValue;
}
const std::shared_ptr<double> &FoodPantries::getLatitude() const noexcept
{
    return latitude_;
}
void FoodPantries::setLatitude(const double &pLatitude) noexcept
{
    latitude_ = std::make_shared<double>(pLatitude);
    dirtyFlag_[9] = true;
}
void FoodPantries::setLatitudeToNull() noexcept
{
    latitude_.reset();
    dirtyFlag_[9] = true;
}

const double &FoodPantries::getValueOfLongitude() const noexcept
{
    static const double defaultValue = double();
    if(longitude_)
        return *longitude_;
    return defaultValue;
}
const std::shared_ptr<double> &FoodPantries::getLongitude() const noexcept
{
    return longitude_;
}
void FoodPantries::setLongitude(const double &pLongitude) noexcept
{
    longitude_ = std::make_shared<double>(pLongitude);
    dirtyFlag_[10] = true;
}
void FoodPantries::setLongitudeToNull() noexcept
{
    longitude_.reset();
    dirtyFlag_[10] = true;
}

const std::string &FoodPantries::getValueOfMealType() const noexcept
{
    static const std::string defaultValue = std::string();
    if(mealType_)
        return *mealType_;
    return defaultValue;
}
const std::shared_ptr<std::string> &FoodPantries::getMealType() const noexcept
{
    return mealType_;
}
void FoodPantries::setMealType(const std::string &pMealType) noexcept
{
    mealType_ = std::make_shared<std::string>(pMealType);
    dirtyFlag_[11] = true;
}
void FoodPantries::setMealType(std::string &&pMealType) noexcept
{
    mealType_ = std::make_shared<std::string>(std::move(pMealType));
    dirtyFlag_[11] = true;
}
void FoodPantries::setMealTypeToNull() noexcept
{
    mealType_.reset();
    dirtyFlag_[11] = true;
}

const std::string &FoodPantries::getValueOfFrequency() const noexcept
{
    static const std::string defaultValue = std::string();
    if(frequency_)
        return *frequency_;
    return defaultValue;
}
const std::shared_ptr<std::string> &FoodPantries::getFrequency() const noexcept
{
    return frequency_;
}
void FoodPantries::setFrequency(const std::string &pFrequency) noexcept
{
    frequency_ = std::make_shared<std::string>(pFrequency);
    dirtyFlag_[12] = true;
}
void FoodPantries::setFrequency(std::string &&pFrequency) noexcept
{
    frequency_ = std::make_shared<std::string>(std::move(pFrequency));
    dirtyFlag_[12] = true;
}
void FoodPantries::setFrequencyToNull() noexcept
{
    frequency_.reset();
    dirtyFlag_[12] = true;
}

const std::string &FoodPantries::getValueOfPhone() const noexcept
{
    static const std::string defaultValue = std::string();
    if(phone_)
        return *phone_;
    return defaultValue;
}
const std::shared_ptr<std::string> &FoodPantries::getPhone() const noexcept
{
    return phone_;
}
void FoodPantries::setPhone(const std::string &pPhone) noexcept
{
    phone_ = std::make_shared<std::string>(pPhone);
    dirtyFlag_[13] = true;
}
void FoodPantries::setPhone(std::string &&pPhone) noexcept
{
    phone_ = std::make_shared<std::string>(std::move(pPhone));
    dirtyFlag_[13] = true;
}
void FoodPantries::setPhoneToNull() noexcept
{
    phone_.reset();
    dirtyFlag_[13] = true;
}

const std::string &FoodPantries::getValueOfProgram() const noexcept
{
    static const std::string defaultValue = std::string();
    if(program_)
        return *program_;
    return defaultValue;
}
const std::shared_ptr<std::string> &FoodPantries::getProgram() const noexcept
{
    return program_;
}
void FoodPantries::setProgram(const std::string &pProgram) noexcept
{
    program_ = std::make_shared<std::string>(pProgram);
    dirtyFlag_[14] = true;
}
void FoodPantries::setProgram(std::string &&pProgram) noexcept
{
    program_ = std::make_shared<std::string>(std::move(pProgram));
    dirtyFlag_[14] = true;
}
void FoodPantries::setProgramToNull() noexcept
{
    program_.reset();
    dirtyFlag_[14] = true;
}

void FoodPantries::updateId(const uint64_t id)
{
}

const std::vector<std::string> &FoodPantries::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "agency",
        "day_of_week",
        "open_time",
        "close_time",
        "street",
        "building",
        "boro",
        "zipcode",
        "latitude",
        "longitude",
        "meal_type",
        "frequency",
        "phone",
        "program"
    };
    return inCols;
}

void FoodPantries::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getAgency())
        {
            binder << getValueOfAgency();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getDayOfWeek())
        {
            binder << getValueOfDayOfWeek();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getOpenTime())
        {
            binder << getValueOfOpenTime();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getCloseTime())
        {
            binder << getValueOfCloseTime();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getStreet())
        {
            binder << getValueOfStreet();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getBuilding())
        {
            binder << getValueOfBuilding();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getBoro())
        {
            binder << getValueOfBoro();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getZipcode())
        {
            binder << getValueOfZipcode();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getLatitude())
        {
            binder << getValueOfLatitude();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getLongitude())
        {
            binder << getValueOfLongitude();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getMealType())
        {
            binder << getValueOfMealType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getFrequency())
        {
            binder << getValueOfFrequency();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[13])
    {
        if(getPhone())
        {
            binder << getValueOfPhone();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[14])
    {
        if(getProgram())
        {
            binder << getValueOfProgram();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> FoodPantries::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    if(dirtyFlag_[10])
    {
        ret.push_back(getColumnName(10));
    }
    if(dirtyFlag_[11])
    {
        ret.push_back(getColumnName(11));
    }
    if(dirtyFlag_[12])
    {
        ret.push_back(getColumnName(12));
    }
    if(dirtyFlag_[13])
    {
        ret.push_back(getColumnName(13));
    }
    if(dirtyFlag_[14])
    {
        ret.push_back(getColumnName(14));
    }
    return ret;
}

void FoodPantries::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getAgency())
        {
            binder << getValueOfAgency();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getDayOfWeek())
        {
            binder << getValueOfDayOfWeek();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getOpenTime())
        {
            binder << getValueOfOpenTime();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getCloseTime())
        {
            binder << getValueOfCloseTime();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getStreet())
        {
            binder << getValueOfStreet();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getBuilding())
        {
            binder << getValueOfBuilding();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getBoro())
        {
            binder << getValueOfBoro();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getZipcode())
        {
            binder << getValueOfZipcode();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getLatitude())
        {
            binder << getValueOfLatitude();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getLongitude())
        {
            binder << getValueOfLongitude();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getMealType())
        {
            binder << getValueOfMealType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getFrequency())
        {
            binder << getValueOfFrequency();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[13])
    {
        if(getPhone())
        {
            binder << getValueOfPhone();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[14])
    {
        if(getProgram())
        {
            binder << getValueOfProgram();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value FoodPantries::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getAgency())
    {
        ret["agency"]=getValueOfAgency();
    }
    else
    {
        ret["agency"]=Json::Value();
    }
    if(getDayOfWeek())
    {
        ret["day_of_week"]=getValueOfDayOfWeek();
    }
    else
    {
        ret["day_of_week"]=Json::Value();
    }
    if(getOpenTime())
    {
        ret["open_time"]=getValueOfOpenTime();
    }
    else
    {
        ret["open_time"]=Json::Value();
    }
    if(getCloseTime())
    {
        ret["close_time"]=getValueOfCloseTime();
    }
    else
    {
        ret["close_time"]=Json::Value();
    }
    if(getStreet())
    {
        ret["street"]=getValueOfStreet();
    }
    else
    {
        ret["street"]=Json::Value();
    }
    if(getBuilding())
    {
        ret["building"]=getValueOfBuilding();
    }
    else
    {
        ret["building"]=Json::Value();
    }
    if(getBoro())
    {
        ret["boro"]=getValueOfBoro();
    }
    else
    {
        ret["boro"]=Json::Value();
    }
    if(getZipcode())
    {
        ret["zipcode"]=getValueOfZipcode();
    }
    else
    {
        ret["zipcode"]=Json::Value();
    }
    if(getLatitude())
    {
        ret["latitude"]=getValueOfLatitude();
    }
    else
    {
        ret["latitude"]=Json::Value();
    }
    if(getLongitude())
    {
        ret["longitude"]=getValueOfLongitude();
    }
    else
    {
        ret["longitude"]=Json::Value();
    }
    if(getMealType())
    {
        ret["meal_type"]=getValueOfMealType();
    }
    else
    {
        ret["meal_type"]=Json::Value();
    }
    if(getFrequency())
    {
        ret["frequency"]=getValueOfFrequency();
    }
    else
    {
        ret["frequency"]=Json::Value();
    }
    if(getPhone())
    {
        ret["phone"]=getValueOfPhone();
    }
    else
    {
        ret["phone"]=Json::Value();
    }
    if(getProgram())
    {
        ret["program"]=getValueOfProgram();
    }
    else
    {
        ret["program"]=Json::Value();
    }
    return ret;
}

std::string FoodPantries::toString() const
{
    return toJson().toStyledString();
}

Json::Value FoodPantries::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 15)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getAgency())
            {
                ret[pMasqueradingVector[1]]=getValueOfAgency();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getDayOfWeek())
            {
                ret[pMasqueradingVector[2]]=getValueOfDayOfWeek();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getOpenTime())
            {
                ret[pMasqueradingVector[3]]=getValueOfOpenTime();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getCloseTime())
            {
                ret[pMasqueradingVector[4]]=getValueOfCloseTime();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getStreet())
            {
                ret[pMasqueradingVector[5]]=getValueOfStreet();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getBuilding())
            {
                ret[pMasqueradingVector[6]]=getValueOfBuilding();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getBoro())
            {
                ret[pMasqueradingVector[7]]=getValueOfBoro();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getZipcode())
            {
                ret[pMasqueradingVector[8]]=getValueOfZipcode();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getLatitude())
            {
                ret[pMasqueradingVector[9]]=getValueOfLatitude();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[10].empty())
        {
            if(getLongitude())
            {
                ret[pMasqueradingVector[10]]=getValueOfLongitude();
            }
            else
            {
                ret[pMasqueradingVector[10]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[11].empty())
        {
            if(getMealType())
            {
                ret[pMasqueradingVector[11]]=getValueOfMealType();
            }
            else
            {
                ret[pMasqueradingVector[11]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[12].empty())
        {
            if(getFrequency())
            {
                ret[pMasqueradingVector[12]]=getValueOfFrequency();
            }
            else
            {
                ret[pMasqueradingVector[12]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[13].empty())
        {
            if(getPhone())
            {
                ret[pMasqueradingVector[13]]=getValueOfPhone();
            }
            else
            {
                ret[pMasqueradingVector[13]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[14].empty())
        {
            if(getProgram())
            {
                ret[pMasqueradingVector[14]]=getValueOfProgram();
            }
            else
            {
                ret[pMasqueradingVector[14]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getAgency())
    {
        ret["agency"]=getValueOfAgency();
    }
    else
    {
        ret["agency"]=Json::Value();
    }
    if(getDayOfWeek())
    {
        ret["day_of_week"]=getValueOfDayOfWeek();
    }
    else
    {
        ret["day_of_week"]=Json::Value();
    }
    if(getOpenTime())
    {
        ret["open_time"]=getValueOfOpenTime();
    }
    else
    {
        ret["open_time"]=Json::Value();
    }
    if(getCloseTime())
    {
        ret["close_time"]=getValueOfCloseTime();
    }
    else
    {
        ret["close_time"]=Json::Value();
    }
    if(getStreet())
    {
        ret["street"]=getValueOfStreet();
    }
    else
    {
        ret["street"]=Json::Value();
    }
    if(getBuilding())
    {
        ret["building"]=getValueOfBuilding();
    }
    else
    {
        ret["building"]=Json::Value();
    }
    if(getBoro())
    {
        ret["boro"]=getValueOfBoro();
    }
    else
    {
        ret["boro"]=Json::Value();
    }
    if(getZipcode())
    {
        ret["zipcode"]=getValueOfZipcode();
    }
    else
    {
        ret["zipcode"]=Json::Value();
    }
    if(getLatitude())
    {
        ret["latitude"]=getValueOfLatitude();
    }
    else
    {
        ret["latitude"]=Json::Value();
    }
    if(getLongitude())
    {
        ret["longitude"]=getValueOfLongitude();
    }
    else
    {
        ret["longitude"]=Json::Value();
    }
    if(getMealType())
    {
        ret["meal_type"]=getValueOfMealType();
    }
    else
    {
        ret["meal_type"]=Json::Value();
    }
    if(getFrequency())
    {
        ret["frequency"]=getValueOfFrequency();
    }
    else
    {
        ret["frequency"]=Json::Value();
    }
    if(getPhone())
    {
        ret["phone"]=getValueOfPhone();
    }
    else
    {
        ret["phone"]=Json::Value();
    }
    if(getProgram())
    {
        ret["program"]=getValueOfProgram();
    }
    else
    {
        ret["program"]=Json::Value();
    }
    return ret;
}

bool FoodPantries::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("agency"))
    {
        if(!validJsonOfField(1, "agency", pJson["agency"], err, true))
            return false;
    }
    else
    {
        err="The agency column cannot be null";
        return false;
    }
    if(pJson.isMember("day_of_week"))
    {
        if(!validJsonOfField(2, "day_of_week", pJson["day_of_week"], err, true))
            return false;
    }
    else
    {
        err="The day_of_week column cannot be null";
        return false;
    }
    if(pJson.isMember("open_time"))
    {
        if(!validJsonOfField(3, "open_time", pJson["open_time"], err, true))
            return false;
    }
    if(pJson.isMember("close_time"))
    {
        if(!validJsonOfField(4, "close_time", pJson["close_time"], err, true))
            return false;
    }
    if(pJson.isMember("street"))
    {
        if(!validJsonOfField(5, "street", pJson["street"], err, true))
            return false;
    }
    if(pJson.isMember("building"))
    {
        if(!validJsonOfField(6, "building", pJson["building"], err, true))
            return false;
    }
    if(pJson.isMember("boro"))
    {
        if(!validJsonOfField(7, "boro", pJson["boro"], err, true))
            return false;
    }
    if(pJson.isMember("zipcode"))
    {
        if(!validJsonOfField(8, "zipcode", pJson["zipcode"], err, true))
            return false;
    }
    if(pJson.isMember("latitude"))
    {
        if(!validJsonOfField(9, "latitude", pJson["latitude"], err, true))
            return false;
    }
    if(pJson.isMember("longitude"))
    {
        if(!validJsonOfField(10, "longitude", pJson["longitude"], err, true))
            return false;
    }
    if(pJson.isMember("meal_type"))
    {
        if(!validJsonOfField(11, "meal_type", pJson["meal_type"], err, true))
            return false;
    }
    if(pJson.isMember("frequency"))
    {
        if(!validJsonOfField(12, "frequency", pJson["frequency"], err, true))
            return false;
    }
    if(pJson.isMember("phone"))
    {
        if(!validJsonOfField(13, "phone", pJson["phone"], err, true))
            return false;
    }
    if(pJson.isMember("program"))
    {
        if(!validJsonOfField(14, "program", pJson["program"], err, true))
            return false;
    }
    return true;
}
bool FoodPantries::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                      const std::vector<std::string> &pMasqueradingVector,
                                                      std::string &err)
{
    if(pMasqueradingVector.size() != 15)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[10].empty())
      {
          if(pJson.isMember(pMasqueradingVector[10]))
          {
              if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[11].empty())
      {
          if(pJson.isMember(pMasqueradingVector[11]))
          {
              if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[12].empty())
      {
          if(pJson.isMember(pMasqueradingVector[12]))
          {
              if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[13].empty())
      {
          if(pJson.isMember(pMasqueradingVector[13]))
          {
              if(!validJsonOfField(13, pMasqueradingVector[13], pJson[pMasqueradingVector[13]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[14].empty())
      {
          if(pJson.isMember(pMasqueradingVector[14]))
          {
              if(!validJsonOfField(14, pMasqueradingVector[14], pJson[pMasqueradingVector[14]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool FoodPantries::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("agency"))
    {
        if(!validJsonOfField(1, "agency", pJson["agency"], err, false))
            return false;
    }
    if(pJson.isMember("day_of_week"))
    {
        if(!validJsonOfField(2, "day_of_week", pJson["day_of_week"], err, false))
            return false;
    }
    if(pJson.isMember("open_time"))
    {
        if(!validJsonOfField(3, "open_time", pJson["open_time"], err, false))
            return false;
    }
    if(pJson.isMember("close_time"))
    {
        if(!validJsonOfField(4, "close_time", pJson["close_time"], err, false))
            return false;
    }
    if(pJson.isMember("street"))
    {
        if(!validJsonOfField(5, "street", pJson["street"], err, false))
            return false;
    }
    if(pJson.isMember("building"))
    {
        if(!validJsonOfField(6, "building", pJson["building"], err, false))
            return false;
    }
    if(pJson.isMember("boro"))
    {
        if(!validJsonOfField(7, "boro", pJson["boro"], err, false))
            return false;
    }
    if(pJson.isMember("zipcode"))
    {
        if(!validJsonOfField(8, "zipcode", pJson["zipcode"], err, false))
            return false;
    }
    if(pJson.isMember("latitude"))
    {
        if(!validJsonOfField(9, "latitude", pJson["latitude"], err, false))
            return false;
    }
    if(pJson.isMember("longitude"))
    {
        if(!validJsonOfField(10, "longitude", pJson["longitude"], err, false))
            return false;
    }
    if(pJson.isMember("meal_type"))
    {
        if(!validJsonOfField(11, "meal_type", pJson["meal_type"], err, false))
            return false;
    }
    if(pJson.isMember("frequency"))
    {
        if(!validJsonOfField(12, "frequency", pJson["frequency"], err, false))
            return false;
    }
    if(pJson.isMember("phone"))
    {
        if(!validJsonOfField(13, "phone", pJson["phone"], err, false))
            return false;
    }
    if(pJson.isMember("program"))
    {
        if(!validJsonOfField(14, "program", pJson["program"], err, false))
            return false;
    }
    return true;
}
bool FoodPantries::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                    const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err)
{
    if(pMasqueradingVector.size() != 15)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
      if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
      {
          if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, false))
              return false;
      }
      if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
      {
          if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, false))
              return false;
      }
      if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
      {
          if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, false))
              return false;
      }
      if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
      {
          if(!validJsonOfField(13, pMasqueradingVector[13], pJson[pMasqueradingVector[13]], err, false))
              return false;
      }
      if(!pMasqueradingVector[14].empty() && pJson.isMember(pMasqueradingVector[14]))
      {
          if(!validJsonOfField(14, pMasqueradingVector[14], pJson[pMasqueradingVector[14]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool FoodPantries::validJsonOfField(size_t index,
                                    const std::string &fieldName,
                                    const Json::Value &pJson,
                                    std::string &err,
                                    bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 9:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isNumeric())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 10:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isNumeric())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 11:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 12:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 13:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 14:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
