/**
 *
 *  FoodItems.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace biteful
{

class FoodItems
{
  public:
    struct Cols
    {
        static const std::string _id;
        static const std::string _menu_id;
        static const std::string _dish_name;
        static const std::string _health_points;
        static const std::string _menu_section;
        static const std::string _dish_desc;
        static const std::string _price;
        static const std::string _last_updated;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = int32_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit FoodItems(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit FoodItems(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    FoodItems(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    FoodItems() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column id  */
    ///Get the value of the column id, returns the default value if the column is null
    const int32_t &getValueOfId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getId() const noexcept;
    ///Set the value of the column id
    void setId(const int32_t &pId) noexcept;

    /**  For column menu_id  */
    ///Get the value of the column menu_id, returns the default value if the column is null
    const int32_t &getValueOfMenuId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getMenuId() const noexcept;
    ///Set the value of the column menu_id
    void setMenuId(const int32_t &pMenuId) noexcept;
    void setMenuIdToNull() noexcept;

    /**  For column dish_name  */
    ///Get the value of the column dish_name, returns the default value if the column is null
    const std::string &getValueOfDishName() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getDishName() const noexcept;
    ///Set the value of the column dish_name
    void setDishName(const std::string &pDishName) noexcept;
    void setDishName(std::string &&pDishName) noexcept;

    /**  For column health_points  */
    ///Get the value of the column health_points, returns the default value if the column is null
    const int32_t &getValueOfHealthPoints() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getHealthPoints() const noexcept;
    ///Set the value of the column health_points
    void setHealthPoints(const int32_t &pHealthPoints) noexcept;
    void setHealthPointsToNull() noexcept;

    /**  For column menu_section  */
    ///Get the value of the column menu_section, returns the default value if the column is null
    const std::string &getValueOfMenuSection() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getMenuSection() const noexcept;
    ///Set the value of the column menu_section
    void setMenuSection(const std::string &pMenuSection) noexcept;
    void setMenuSection(std::string &&pMenuSection) noexcept;
    void setMenuSectionToNull() noexcept;

    /**  For column dish_desc  */
    ///Get the value of the column dish_desc, returns the default value if the column is null
    const std::string &getValueOfDishDesc() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getDishDesc() const noexcept;
    ///Set the value of the column dish_desc
    void setDishDesc(const std::string &pDishDesc) noexcept;
    void setDishDesc(std::string &&pDishDesc) noexcept;
    void setDishDescToNull() noexcept;

    /**  For column price  */
    ///Get the value of the column price, returns the default value if the column is null
    const std::string &getValueOfPrice() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getPrice() const noexcept;
    ///Set the value of the column price
    void setPrice(const std::string &pPrice) noexcept;
    void setPrice(std::string &&pPrice) noexcept;

    /**  For column last_updated  */
    ///Get the value of the column last_updated, returns the default value if the column is null
    const ::trantor::Date &getValueOfLastUpdated() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getLastUpdated() const noexcept;
    ///Set the value of the column last_updated
    void setLastUpdated(const ::trantor::Date &pLastUpdated) noexcept;
    void setLastUpdatedToNull() noexcept;


    static size_t getColumnNumber() noexcept {  return 8;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<FoodItems>;
    friend drogon::orm::BaseBuilder<FoodItems, true, true>;
    friend drogon::orm::BaseBuilder<FoodItems, true, false>;
    friend drogon::orm::BaseBuilder<FoodItems, false, true>;
    friend drogon::orm::BaseBuilder<FoodItems, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<FoodItems>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<int32_t> id_;
    std::shared_ptr<int32_t> menuId_;
    std::shared_ptr<std::string> dishName_;
    std::shared_ptr<int32_t> healthPoints_;
    std::shared_ptr<std::string> menuSection_;
    std::shared_ptr<std::string> dishDesc_;
    std::shared_ptr<std::string> price_;
    std::shared_ptr<::trantor::Date> lastUpdated_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[8]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where id = $1";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where id = $1";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
            sql += "id,";
            ++parametersCount;
        if(dirtyFlag_[1])
        {
            sql += "menu_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "dish_name,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "health_points,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "menu_section,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "dish_desc,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "price,";
            ++parametersCount;
        }
        sql += "last_updated,";
        ++parametersCount;
        if(!dirtyFlag_[7])
        {
            needSelection=true;
        }
        needSelection=true;
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        sql +="default,";
        if(dirtyFlag_[1])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[2])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[3])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[4])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[5])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[6])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[7])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace biteful
} // namespace drogon_model
