/**
 *
 *  FoodItems.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "FoodItems.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::biteful;

const std::string FoodItems::Cols::_id = "\"id\"";
const std::string FoodItems::Cols::_menu_id = "\"menu_id\"";
const std::string FoodItems::Cols::_dish_name = "\"dish_name\"";
const std::string FoodItems::Cols::_health_points = "\"health_points\"";
const std::string FoodItems::Cols::_menu_section = "\"menu_section\"";
const std::string FoodItems::Cols::_dish_desc = "\"dish_desc\"";
const std::string FoodItems::Cols::_price = "\"price\"";
const std::string FoodItems::Cols::_last_updated = "\"last_updated\"";
const std::string FoodItems::primaryKeyName = "id";
const bool FoodItems::hasPrimaryKey = true;
const std::string FoodItems::tableName = "\"food_items\"";

const std::vector<typename FoodItems::MetaData> FoodItems::metaData_={
{"id","int32_t","integer",4,1,1,1},
{"menu_id","int32_t","integer",4,0,0,0},
{"dish_name","std::string","text",0,0,0,1},
{"health_points","int32_t","integer",4,0,0,0},
{"menu_section","std::string","text",0,0,0,0},
{"dish_desc","std::string","text",0,0,0,0},
{"price","std::string","numeric",0,0,0,1},
{"last_updated","::trantor::Date","timestamp without time zone",0,0,0,0}
};
const std::string &FoodItems::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
FoodItems::FoodItems(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int32_t>(r["id"].as<int32_t>());
        }
        if(!r["menu_id"].isNull())
        {
            menuId_=std::make_shared<int32_t>(r["menu_id"].as<int32_t>());
        }
        if(!r["dish_name"].isNull())
        {
            dishName_=std::make_shared<std::string>(r["dish_name"].as<std::string>());
        }
        if(!r["health_points"].isNull())
        {
            healthPoints_=std::make_shared<int32_t>(r["health_points"].as<int32_t>());
        }
        if(!r["menu_section"].isNull())
        {
            menuSection_=std::make_shared<std::string>(r["menu_section"].as<std::string>());
        }
        if(!r["dish_desc"].isNull())
        {
            dishDesc_=std::make_shared<std::string>(r["dish_desc"].as<std::string>());
        }
        if(!r["price"].isNull())
        {
            price_=std::make_shared<std::string>(r["price"].as<std::string>());
        }
        if(!r["last_updated"].isNull())
        {
            auto timeStr = r["last_updated"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastUpdated_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 8 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            menuId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            dishName_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            healthPoints_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            menuSection_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            dishDesc_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            price_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastUpdated_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }

}

FoodItems::FoodItems(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 8)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            menuId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            dishName_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            healthPoints_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            menuSection_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            dishDesc_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            price_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[7]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastUpdated_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

FoodItems::FoodItems(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("menu_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["menu_id"].isNull())
        {
            menuId_=std::make_shared<int32_t>((int32_t)pJson["menu_id"].asInt64());
        }
    }
    if(pJson.isMember("dish_name"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["dish_name"].isNull())
        {
            dishName_=std::make_shared<std::string>(pJson["dish_name"].asString());
        }
    }
    if(pJson.isMember("health_points"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["health_points"].isNull())
        {
            healthPoints_=std::make_shared<int32_t>((int32_t)pJson["health_points"].asInt64());
        }
    }
    if(pJson.isMember("menu_section"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["menu_section"].isNull())
        {
            menuSection_=std::make_shared<std::string>(pJson["menu_section"].asString());
        }
    }
    if(pJson.isMember("dish_desc"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["dish_desc"].isNull())
        {
            dishDesc_=std::make_shared<std::string>(pJson["dish_desc"].asString());
        }
    }
    if(pJson.isMember("price"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["price"].isNull())
        {
            price_=std::make_shared<std::string>(pJson["price"].asString());
        }
    }
    if(pJson.isMember("last_updated"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["last_updated"].isNull())
        {
            auto timeStr = pJson["last_updated"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastUpdated_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void FoodItems::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 8)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            menuId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            dishName_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            healthPoints_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            menuSection_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            dishDesc_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            price_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[7]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastUpdated_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void FoodItems::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("menu_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["menu_id"].isNull())
        {
            menuId_=std::make_shared<int32_t>((int32_t)pJson["menu_id"].asInt64());
        }
    }
    if(pJson.isMember("dish_name"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["dish_name"].isNull())
        {
            dishName_=std::make_shared<std::string>(pJson["dish_name"].asString());
        }
    }
    if(pJson.isMember("health_points"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["health_points"].isNull())
        {
            healthPoints_=std::make_shared<int32_t>((int32_t)pJson["health_points"].asInt64());
        }
    }
    if(pJson.isMember("menu_section"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["menu_section"].isNull())
        {
            menuSection_=std::make_shared<std::string>(pJson["menu_section"].asString());
        }
    }
    if(pJson.isMember("dish_desc"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["dish_desc"].isNull())
        {
            dishDesc_=std::make_shared<std::string>(pJson["dish_desc"].asString());
        }
    }
    if(pJson.isMember("price"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["price"].isNull())
        {
            price_=std::make_shared<std::string>(pJson["price"].asString());
        }
    }
    if(pJson.isMember("last_updated"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["last_updated"].isNull())
        {
            auto timeStr = pJson["last_updated"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastUpdated_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

const int32_t &FoodItems::getValueOfId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &FoodItems::getId() const noexcept
{
    return id_;
}
void FoodItems::setId(const int32_t &pId) noexcept
{
    id_ = std::make_shared<int32_t>(pId);
    dirtyFlag_[0] = true;
}
const typename FoodItems::PrimaryKeyType & FoodItems::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const int32_t &FoodItems::getValueOfMenuId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(menuId_)
        return *menuId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &FoodItems::getMenuId() const noexcept
{
    return menuId_;
}
void FoodItems::setMenuId(const int32_t &pMenuId) noexcept
{
    menuId_ = std::make_shared<int32_t>(pMenuId);
    dirtyFlag_[1] = true;
}
void FoodItems::setMenuIdToNull() noexcept
{
    menuId_.reset();
    dirtyFlag_[1] = true;
}

const std::string &FoodItems::getValueOfDishName() const noexcept
{
    static const std::string defaultValue = std::string();
    if(dishName_)
        return *dishName_;
    return defaultValue;
}
const std::shared_ptr<std::string> &FoodItems::getDishName() const noexcept
{
    return dishName_;
}
void FoodItems::setDishName(const std::string &pDishName) noexcept
{
    dishName_ = std::make_shared<std::string>(pDishName);
    dirtyFlag_[2] = true;
}
void FoodItems::setDishName(std::string &&pDishName) noexcept
{
    dishName_ = std::make_shared<std::string>(std::move(pDishName));
    dirtyFlag_[2] = true;
}

const int32_t &FoodItems::getValueOfHealthPoints() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(healthPoints_)
        return *healthPoints_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &FoodItems::getHealthPoints() const noexcept
{
    return healthPoints_;
}
void FoodItems::setHealthPoints(const int32_t &pHealthPoints) noexcept
{
    healthPoints_ = std::make_shared<int32_t>(pHealthPoints);
    dirtyFlag_[3] = true;
}
void FoodItems::setHealthPointsToNull() noexcept
{
    healthPoints_.reset();
    dirtyFlag_[3] = true;
}

const std::string &FoodItems::getValueOfMenuSection() const noexcept
{
    static const std::string defaultValue = std::string();
    if(menuSection_)
        return *menuSection_;
    return defaultValue;
}
const std::shared_ptr<std::string> &FoodItems::getMenuSection() const noexcept
{
    return menuSection_;
}
void FoodItems::setMenuSection(const std::string &pMenuSection) noexcept
{
    menuSection_ = std::make_shared<std::string>(pMenuSection);
    dirtyFlag_[4] = true;
}
void FoodItems::setMenuSection(std::string &&pMenuSection) noexcept
{
    menuSection_ = std::make_shared<std::string>(std::move(pMenuSection));
    dirtyFlag_[4] = true;
}
void FoodItems::setMenuSectionToNull() noexcept
{
    menuSection_.reset();
    dirtyFlag_[4] = true;
}

const std::string &FoodItems::getValueOfDishDesc() const noexcept
{
    static const std::string defaultValue = std::string();
    if(dishDesc_)
        return *dishDesc_;
    return defaultValue;
}
const std::shared_ptr<std::string> &FoodItems::getDishDesc() const noexcept
{
    return dishDesc_;
}
void FoodItems::setDishDesc(const std::string &pDishDesc) noexcept
{
    dishDesc_ = std::make_shared<std::string>(pDishDesc);
    dirtyFlag_[5] = true;
}
void FoodItems::setDishDesc(std::string &&pDishDesc) noexcept
{
    dishDesc_ = std::make_shared<std::string>(std::move(pDishDesc));
    dirtyFlag_[5] = true;
}
void FoodItems::setDishDescToNull() noexcept
{
    dishDesc_.reset();
    dirtyFlag_[5] = true;
}

const std::string &FoodItems::getValueOfPrice() const noexcept
{
    static const std::string defaultValue = std::string();
    if(price_)
        return *price_;
    return defaultValue;
}
const std::shared_ptr<std::string> &FoodItems::getPrice() const noexcept
{
    return price_;
}
void FoodItems::setPrice(const std::string &pPrice) noexcept
{
    price_ = std::make_shared<std::string>(pPrice);
    dirtyFlag_[6] = true;
}
void FoodItems::setPrice(std::string &&pPrice) noexcept
{
    price_ = std::make_shared<std::string>(std::move(pPrice));
    dirtyFlag_[6] = true;
}

const ::trantor::Date &FoodItems::getValueOfLastUpdated() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(lastUpdated_)
        return *lastUpdated_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &FoodItems::getLastUpdated() const noexcept
{
    return lastUpdated_;
}
void FoodItems::setLastUpdated(const ::trantor::Date &pLastUpdated) noexcept
{
    lastUpdated_ = std::make_shared<::trantor::Date>(pLastUpdated);
    dirtyFlag_[7] = true;
}
void FoodItems::setLastUpdatedToNull() noexcept
{
    lastUpdated_.reset();
    dirtyFlag_[7] = true;
}

void FoodItems::updateId(const uint64_t id)
{
}

const std::vector<std::string> &FoodItems::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "menu_id",
        "dish_name",
        "health_points",
        "menu_section",
        "dish_desc",
        "price",
        "last_updated"
    };
    return inCols;
}

void FoodItems::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getMenuId())
        {
            binder << getValueOfMenuId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getDishName())
        {
            binder << getValueOfDishName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getHealthPoints())
        {
            binder << getValueOfHealthPoints();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getMenuSection())
        {
            binder << getValueOfMenuSection();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getDishDesc())
        {
            binder << getValueOfDishDesc();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getPrice())
        {
            binder << getValueOfPrice();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getLastUpdated())
        {
            binder << getValueOfLastUpdated();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> FoodItems::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    return ret;
}

void FoodItems::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getMenuId())
        {
            binder << getValueOfMenuId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getDishName())
        {
            binder << getValueOfDishName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getHealthPoints())
        {
            binder << getValueOfHealthPoints();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getMenuSection())
        {
            binder << getValueOfMenuSection();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getDishDesc())
        {
            binder << getValueOfDishDesc();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getPrice())
        {
            binder << getValueOfPrice();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getLastUpdated())
        {
            binder << getValueOfLastUpdated();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value FoodItems::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getMenuId())
    {
        ret["menu_id"]=getValueOfMenuId();
    }
    else
    {
        ret["menu_id"]=Json::Value();
    }
    if(getDishName())
    {
        ret["dish_name"]=getValueOfDishName();
    }
    else
    {
        ret["dish_name"]=Json::Value();
    }
    if(getHealthPoints())
    {
        ret["health_points"]=getValueOfHealthPoints();
    }
    else
    {
        ret["health_points"]=Json::Value();
    }
    if(getMenuSection())
    {
        ret["menu_section"]=getValueOfMenuSection();
    }
    else
    {
        ret["menu_section"]=Json::Value();
    }
    if(getDishDesc())
    {
        ret["dish_desc"]=getValueOfDishDesc();
    }
    else
    {
        ret["dish_desc"]=Json::Value();
    }
    if(getPrice())
    {
        ret["price"]=getValueOfPrice();
    }
    else
    {
        ret["price"]=Json::Value();
    }
    if(getLastUpdated())
    {
        ret["last_updated"]=getLastUpdated()->toDbStringLocal();
    }
    else
    {
        ret["last_updated"]=Json::Value();
    }
    return ret;
}

std::string FoodItems::toString() const
{
    return toJson().toStyledString();
}

Json::Value FoodItems::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 8)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getMenuId())
            {
                ret[pMasqueradingVector[1]]=getValueOfMenuId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getDishName())
            {
                ret[pMasqueradingVector[2]]=getValueOfDishName();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getHealthPoints())
            {
                ret[pMasqueradingVector[3]]=getValueOfHealthPoints();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getMenuSection())
            {
                ret[pMasqueradingVector[4]]=getValueOfMenuSection();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getDishDesc())
            {
                ret[pMasqueradingVector[5]]=getValueOfDishDesc();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getPrice())
            {
                ret[pMasqueradingVector[6]]=getValueOfPrice();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getLastUpdated())
            {
                ret[pMasqueradingVector[7]]=getLastUpdated()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getMenuId())
    {
        ret["menu_id"]=getValueOfMenuId();
    }
    else
    {
        ret["menu_id"]=Json::Value();
    }
    if(getDishName())
    {
        ret["dish_name"]=getValueOfDishName();
    }
    else
    {
        ret["dish_name"]=Json::Value();
    }
    if(getHealthPoints())
    {
        ret["health_points"]=getValueOfHealthPoints();
    }
    else
    {
        ret["health_points"]=Json::Value();
    }
    if(getMenuSection())
    {
        ret["menu_section"]=getValueOfMenuSection();
    }
    else
    {
        ret["menu_section"]=Json::Value();
    }
    if(getDishDesc())
    {
        ret["dish_desc"]=getValueOfDishDesc();
    }
    else
    {
        ret["dish_desc"]=Json::Value();
    }
    if(getPrice())
    {
        ret["price"]=getValueOfPrice();
    }
    else
    {
        ret["price"]=Json::Value();
    }
    if(getLastUpdated())
    {
        ret["last_updated"]=getLastUpdated()->toDbStringLocal();
    }
    else
    {
        ret["last_updated"]=Json::Value();
    }
    return ret;
}

bool FoodItems::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("menu_id"))
    {
        if(!validJsonOfField(1, "menu_id", pJson["menu_id"], err, true))
            return false;
    }
    if(pJson.isMember("dish_name"))
    {
        if(!validJsonOfField(2, "dish_name", pJson["dish_name"], err, true))
            return false;
    }
    else
    {
        err="The dish_name column cannot be null";
        return false;
    }
    if(pJson.isMember("health_points"))
    {
        if(!validJsonOfField(3, "health_points", pJson["health_points"], err, true))
            return false;
    }
    if(pJson.isMember("menu_section"))
    {
        if(!validJsonOfField(4, "menu_section", pJson["menu_section"], err, true))
            return false;
    }
    if(pJson.isMember("dish_desc"))
    {
        if(!validJsonOfField(5, "dish_desc", pJson["dish_desc"], err, true))
            return false;
    }
    if(pJson.isMember("price"))
    {
        if(!validJsonOfField(6, "price", pJson["price"], err, true))
            return false;
    }
    else
    {
        err="The price column cannot be null";
        return false;
    }
    if(pJson.isMember("last_updated"))
    {
        if(!validJsonOfField(7, "last_updated", pJson["last_updated"], err, true))
            return false;
    }
    return true;
}
bool FoodItems::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                   const std::vector<std::string> &pMasqueradingVector,
                                                   std::string &err)
{
    if(pMasqueradingVector.size() != 8)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[6] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool FoodItems::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("menu_id"))
    {
        if(!validJsonOfField(1, "menu_id", pJson["menu_id"], err, false))
            return false;
    }
    if(pJson.isMember("dish_name"))
    {
        if(!validJsonOfField(2, "dish_name", pJson["dish_name"], err, false))
            return false;
    }
    if(pJson.isMember("health_points"))
    {
        if(!validJsonOfField(3, "health_points", pJson["health_points"], err, false))
            return false;
    }
    if(pJson.isMember("menu_section"))
    {
        if(!validJsonOfField(4, "menu_section", pJson["menu_section"], err, false))
            return false;
    }
    if(pJson.isMember("dish_desc"))
    {
        if(!validJsonOfField(5, "dish_desc", pJson["dish_desc"], err, false))
            return false;
    }
    if(pJson.isMember("price"))
    {
        if(!validJsonOfField(6, "price", pJson["price"], err, false))
            return false;
    }
    if(pJson.isMember("last_updated"))
    {
        if(!validJsonOfField(7, "last_updated", pJson["last_updated"], err, false))
            return false;
    }
    return true;
}
bool FoodItems::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                 const std::vector<std::string> &pMasqueradingVector,
                                                 std::string &err)
{
    if(pMasqueradingVector.size() != 8)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool FoodItems::validJsonOfField(size_t index,
                                 const std::string &fieldName,
                                 const Json::Value &pJson,
                                 std::string &err,
                                 bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
