/**
 *
 *  Restaurants.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Restaurants.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::biteful;

const std::string Restaurants::Cols::_camis = "\"camis\"";
const std::string Restaurants::Cols::_name = "\"name\"";
const std::string Restaurants::Cols::_boro = "\"boro\"";
const std::string Restaurants::Cols::_building = "\"building\"";
const std::string Restaurants::Cols::_street = "\"street\"";
const std::string Restaurants::Cols::_zipcode = "\"zipcode\"";
const std::string Restaurants::Cols::_phone = "\"phone\"";
const std::string Restaurants::Cols::_cuisine = "\"cuisine\"";
const std::string Restaurants::Cols::_inspection_date = "\"inspection_date\"";
const std::string Restaurants::Cols::_grade = "\"grade\"";
const std::string Restaurants::Cols::_latitude = "\"latitude\"";
const std::string Restaurants::Cols::_longitude = "\"longitude\"";
const std::string Restaurants::Cols::_last_updated = "\"last_updated\"";
const std::string Restaurants::primaryKeyName = "camis";
const bool Restaurants::hasPrimaryKey = true;
const std::string Restaurants::tableName = "\"restaurants\"";

const std::vector<typename Restaurants::MetaData> Restaurants::metaData_={
{"camis","int32_t","integer",4,0,1,1},
{"name","std::string","text",0,0,0,0},
{"boro","std::string","text",0,0,0,0},
{"building","std::string","text",0,0,0,0},
{"street","std::string","text",0,0,0,0},
{"zipcode","std::string","text",0,0,0,0},
{"phone","std::string","text",0,0,0,0},
{"cuisine","std::string","text",0,0,0,0},
{"inspection_date","::trantor::Date","date",0,0,0,0},
{"grade","std::string","text",0,0,0,0},
{"latitude","double","double precision",8,0,0,0},
{"longitude","double","double precision",8,0,0,0},
{"last_updated","::trantor::Date","timestamp without time zone",0,0,0,0}
};
const std::string &Restaurants::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Restaurants::Restaurants(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["camis"].isNull())
        {
            camis_=std::make_shared<int32_t>(r["camis"].as<int32_t>());
        }
        if(!r["name"].isNull())
        {
            name_=std::make_shared<std::string>(r["name"].as<std::string>());
        }
        if(!r["boro"].isNull())
        {
            boro_=std::make_shared<std::string>(r["boro"].as<std::string>());
        }
        if(!r["building"].isNull())
        {
            building_=std::make_shared<std::string>(r["building"].as<std::string>());
        }
        if(!r["street"].isNull())
        {
            street_=std::make_shared<std::string>(r["street"].as<std::string>());
        }
        if(!r["zipcode"].isNull())
        {
            zipcode_=std::make_shared<std::string>(r["zipcode"].as<std::string>());
        }
        if(!r["phone"].isNull())
        {
            phone_=std::make_shared<std::string>(r["phone"].as<std::string>());
        }
        if(!r["cuisine"].isNull())
        {
            cuisine_=std::make_shared<std::string>(r["cuisine"].as<std::string>());
        }
        if(!r["inspection_date"].isNull())
        {
            auto daysStr = r["inspection_date"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            inspectionDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
        if(!r["grade"].isNull())
        {
            grade_=std::make_shared<std::string>(r["grade"].as<std::string>());
        }
        if(!r["latitude"].isNull())
        {
            latitude_=std::make_shared<double>(r["latitude"].as<double>());
        }
        if(!r["longitude"].isNull())
        {
            longitude_=std::make_shared<double>(r["longitude"].as<double>());
        }
        if(!r["last_updated"].isNull())
        {
            auto timeStr = r["last_updated"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastUpdated_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 13 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            camis_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            name_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            boro_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            building_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            street_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            zipcode_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            phone_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            cuisine_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            auto daysStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            inspectionDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            grade_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 10;
        if(!r[index].isNull())
        {
            latitude_=std::make_shared<double>(r[index].as<double>());
        }
        index = offset + 11;
        if(!r[index].isNull())
        {
            longitude_=std::make_shared<double>(r[index].as<double>());
        }
        index = offset + 12;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastUpdated_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }

}

Restaurants::Restaurants(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 13)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            camis_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            name_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            boro_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            building_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            street_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            zipcode_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            phone_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            cuisine_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            auto daysStr = pJson[pMasqueradingVector[8]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            inspectionDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            grade_=std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            latitude_=std::make_shared<double>(pJson[pMasqueradingVector[10]].asDouble());
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            longitude_=std::make_shared<double>(pJson[pMasqueradingVector[11]].asDouble());
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[12]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastUpdated_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

Restaurants::Restaurants(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("camis"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["camis"].isNull())
        {
            camis_=std::make_shared<int32_t>((int32_t)pJson["camis"].asInt64());
        }
    }
    if(pJson.isMember("name"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["name"].isNull())
        {
            name_=std::make_shared<std::string>(pJson["name"].asString());
        }
    }
    if(pJson.isMember("boro"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["boro"].isNull())
        {
            boro_=std::make_shared<std::string>(pJson["boro"].asString());
        }
    }
    if(pJson.isMember("building"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["building"].isNull())
        {
            building_=std::make_shared<std::string>(pJson["building"].asString());
        }
    }
    if(pJson.isMember("street"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["street"].isNull())
        {
            street_=std::make_shared<std::string>(pJson["street"].asString());
        }
    }
    if(pJson.isMember("zipcode"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["zipcode"].isNull())
        {
            zipcode_=std::make_shared<std::string>(pJson["zipcode"].asString());
        }
    }
    if(pJson.isMember("phone"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["phone"].isNull())
        {
            phone_=std::make_shared<std::string>(pJson["phone"].asString());
        }
    }
    if(pJson.isMember("cuisine"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["cuisine"].isNull())
        {
            cuisine_=std::make_shared<std::string>(pJson["cuisine"].asString());
        }
    }
    if(pJson.isMember("inspection_date"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["inspection_date"].isNull())
        {
            auto daysStr = pJson["inspection_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            inspectionDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(pJson.isMember("grade"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["grade"].isNull())
        {
            grade_=std::make_shared<std::string>(pJson["grade"].asString());
        }
    }
    if(pJson.isMember("latitude"))
    {
        dirtyFlag_[10]=true;
        if(!pJson["latitude"].isNull())
        {
            latitude_=std::make_shared<double>(pJson["latitude"].asDouble());
        }
    }
    if(pJson.isMember("longitude"))
    {
        dirtyFlag_[11]=true;
        if(!pJson["longitude"].isNull())
        {
            longitude_=std::make_shared<double>(pJson["longitude"].asDouble());
        }
    }
    if(pJson.isMember("last_updated"))
    {
        dirtyFlag_[12]=true;
        if(!pJson["last_updated"].isNull())
        {
            auto timeStr = pJson["last_updated"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastUpdated_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void Restaurants::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 13)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            camis_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            name_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            boro_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            building_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            street_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            zipcode_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            phone_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            cuisine_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            auto daysStr = pJson[pMasqueradingVector[8]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            inspectionDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            grade_=std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            latitude_=std::make_shared<double>(pJson[pMasqueradingVector[10]].asDouble());
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            longitude_=std::make_shared<double>(pJson[pMasqueradingVector[11]].asDouble());
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[12]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastUpdated_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void Restaurants::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("camis"))
    {
        if(!pJson["camis"].isNull())
        {
            camis_=std::make_shared<int32_t>((int32_t)pJson["camis"].asInt64());
        }
    }
    if(pJson.isMember("name"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["name"].isNull())
        {
            name_=std::make_shared<std::string>(pJson["name"].asString());
        }
    }
    if(pJson.isMember("boro"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["boro"].isNull())
        {
            boro_=std::make_shared<std::string>(pJson["boro"].asString());
        }
    }
    if(pJson.isMember("building"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["building"].isNull())
        {
            building_=std::make_shared<std::string>(pJson["building"].asString());
        }
    }
    if(pJson.isMember("street"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["street"].isNull())
        {
            street_=std::make_shared<std::string>(pJson["street"].asString());
        }
    }
    if(pJson.isMember("zipcode"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["zipcode"].isNull())
        {
            zipcode_=std::make_shared<std::string>(pJson["zipcode"].asString());
        }
    }
    if(pJson.isMember("phone"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["phone"].isNull())
        {
            phone_=std::make_shared<std::string>(pJson["phone"].asString());
        }
    }
    if(pJson.isMember("cuisine"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["cuisine"].isNull())
        {
            cuisine_=std::make_shared<std::string>(pJson["cuisine"].asString());
        }
    }
    if(pJson.isMember("inspection_date"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["inspection_date"].isNull())
        {
            auto daysStr = pJson["inspection_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            inspectionDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(pJson.isMember("grade"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["grade"].isNull())
        {
            grade_=std::make_shared<std::string>(pJson["grade"].asString());
        }
    }
    if(pJson.isMember("latitude"))
    {
        dirtyFlag_[10] = true;
        if(!pJson["latitude"].isNull())
        {
            latitude_=std::make_shared<double>(pJson["latitude"].asDouble());
        }
    }
    if(pJson.isMember("longitude"))
    {
        dirtyFlag_[11] = true;
        if(!pJson["longitude"].isNull())
        {
            longitude_=std::make_shared<double>(pJson["longitude"].asDouble());
        }
    }
    if(pJson.isMember("last_updated"))
    {
        dirtyFlag_[12] = true;
        if(!pJson["last_updated"].isNull())
        {
            auto timeStr = pJson["last_updated"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastUpdated_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

const int32_t &Restaurants::getValueOfCamis() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(camis_)
        return *camis_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Restaurants::getCamis() const noexcept
{
    return camis_;
}
void Restaurants::setCamis(const int32_t &pCamis) noexcept
{
    camis_ = std::make_shared<int32_t>(pCamis);
    dirtyFlag_[0] = true;
}
const typename Restaurants::PrimaryKeyType & Restaurants::getPrimaryKey() const
{
    assert(camis_);
    return *camis_;
}

const std::string &Restaurants::getValueOfName() const noexcept
{
    static const std::string defaultValue = std::string();
    if(name_)
        return *name_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Restaurants::getName() const noexcept
{
    return name_;
}
void Restaurants::setName(const std::string &pName) noexcept
{
    name_ = std::make_shared<std::string>(pName);
    dirtyFlag_[1] = true;
}
void Restaurants::setName(std::string &&pName) noexcept
{
    name_ = std::make_shared<std::string>(std::move(pName));
    dirtyFlag_[1] = true;
}
void Restaurants::setNameToNull() noexcept
{
    name_.reset();
    dirtyFlag_[1] = true;
}

const std::string &Restaurants::getValueOfBoro() const noexcept
{
    static const std::string defaultValue = std::string();
    if(boro_)
        return *boro_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Restaurants::getBoro() const noexcept
{
    return boro_;
}
void Restaurants::setBoro(const std::string &pBoro) noexcept
{
    boro_ = std::make_shared<std::string>(pBoro);
    dirtyFlag_[2] = true;
}
void Restaurants::setBoro(std::string &&pBoro) noexcept
{
    boro_ = std::make_shared<std::string>(std::move(pBoro));
    dirtyFlag_[2] = true;
}
void Restaurants::setBoroToNull() noexcept
{
    boro_.reset();
    dirtyFlag_[2] = true;
}

const std::string &Restaurants::getValueOfBuilding() const noexcept
{
    static const std::string defaultValue = std::string();
    if(building_)
        return *building_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Restaurants::getBuilding() const noexcept
{
    return building_;
}
void Restaurants::setBuilding(const std::string &pBuilding) noexcept
{
    building_ = std::make_shared<std::string>(pBuilding);
    dirtyFlag_[3] = true;
}
void Restaurants::setBuilding(std::string &&pBuilding) noexcept
{
    building_ = std::make_shared<std::string>(std::move(pBuilding));
    dirtyFlag_[3] = true;
}
void Restaurants::setBuildingToNull() noexcept
{
    building_.reset();
    dirtyFlag_[3] = true;
}

const std::string &Restaurants::getValueOfStreet() const noexcept
{
    static const std::string defaultValue = std::string();
    if(street_)
        return *street_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Restaurants::getStreet() const noexcept
{
    return street_;
}
void Restaurants::setStreet(const std::string &pStreet) noexcept
{
    street_ = std::make_shared<std::string>(pStreet);
    dirtyFlag_[4] = true;
}
void Restaurants::setStreet(std::string &&pStreet) noexcept
{
    street_ = std::make_shared<std::string>(std::move(pStreet));
    dirtyFlag_[4] = true;
}
void Restaurants::setStreetToNull() noexcept
{
    street_.reset();
    dirtyFlag_[4] = true;
}

const std::string &Restaurants::getValueOfZipcode() const noexcept
{
    static const std::string defaultValue = std::string();
    if(zipcode_)
        return *zipcode_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Restaurants::getZipcode() const noexcept
{
    return zipcode_;
}
void Restaurants::setZipcode(const std::string &pZipcode) noexcept
{
    zipcode_ = std::make_shared<std::string>(pZipcode);
    dirtyFlag_[5] = true;
}
void Restaurants::setZipcode(std::string &&pZipcode) noexcept
{
    zipcode_ = std::make_shared<std::string>(std::move(pZipcode));
    dirtyFlag_[5] = true;
}
void Restaurants::setZipcodeToNull() noexcept
{
    zipcode_.reset();
    dirtyFlag_[5] = true;
}

const std::string &Restaurants::getValueOfPhone() const noexcept
{
    static const std::string defaultValue = std::string();
    if(phone_)
        return *phone_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Restaurants::getPhone() const noexcept
{
    return phone_;
}
void Restaurants::setPhone(const std::string &pPhone) noexcept
{
    phone_ = std::make_shared<std::string>(pPhone);
    dirtyFlag_[6] = true;
}
void Restaurants::setPhone(std::string &&pPhone) noexcept
{
    phone_ = std::make_shared<std::string>(std::move(pPhone));
    dirtyFlag_[6] = true;
}
void Restaurants::setPhoneToNull() noexcept
{
    phone_.reset();
    dirtyFlag_[6] = true;
}

const std::string &Restaurants::getValueOfCuisine() const noexcept
{
    static const std::string defaultValue = std::string();
    if(cuisine_)
        return *cuisine_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Restaurants::getCuisine() const noexcept
{
    return cuisine_;
}
void Restaurants::setCuisine(const std::string &pCuisine) noexcept
{
    cuisine_ = std::make_shared<std::string>(pCuisine);
    dirtyFlag_[7] = true;
}
void Restaurants::setCuisine(std::string &&pCuisine) noexcept
{
    cuisine_ = std::make_shared<std::string>(std::move(pCuisine));
    dirtyFlag_[7] = true;
}
void Restaurants::setCuisineToNull() noexcept
{
    cuisine_.reset();
    dirtyFlag_[7] = true;
}

const ::trantor::Date &Restaurants::getValueOfInspectionDate() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(inspectionDate_)
        return *inspectionDate_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &Restaurants::getInspectionDate() const noexcept
{
    return inspectionDate_;
}
void Restaurants::setInspectionDate(const ::trantor::Date &pInspectionDate) noexcept
{
    inspectionDate_ = std::make_shared<::trantor::Date>(pInspectionDate.roundDay());
    dirtyFlag_[8] = true;
}
void Restaurants::setInspectionDateToNull() noexcept
{
    inspectionDate_.reset();
    dirtyFlag_[8] = true;
}

const std::string &Restaurants::getValueOfGrade() const noexcept
{
    static const std::string defaultValue = std::string();
    if(grade_)
        return *grade_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Restaurants::getGrade() const noexcept
{
    return grade_;
}
void Restaurants::setGrade(const std::string &pGrade) noexcept
{
    grade_ = std::make_shared<std::string>(pGrade);
    dirtyFlag_[9] = true;
}
void Restaurants::setGrade(std::string &&pGrade) noexcept
{
    grade_ = std::make_shared<std::string>(std::move(pGrade));
    dirtyFlag_[9] = true;
}
void Restaurants::setGradeToNull() noexcept
{
    grade_.reset();
    dirtyFlag_[9] = true;
}

const double &Restaurants::getValueOfLatitude() const noexcept
{
    static const double defaultValue = double();
    if(latitude_)
        return *latitude_;
    return defaultValue;
}
const std::shared_ptr<double> &Restaurants::getLatitude() const noexcept
{
    return latitude_;
}
void Restaurants::setLatitude(const double &pLatitude) noexcept
{
    latitude_ = std::make_shared<double>(pLatitude);
    dirtyFlag_[10] = true;
}
void Restaurants::setLatitudeToNull() noexcept
{
    latitude_.reset();
    dirtyFlag_[10] = true;
}

const double &Restaurants::getValueOfLongitude() const noexcept
{
    static const double defaultValue = double();
    if(longitude_)
        return *longitude_;
    return defaultValue;
}
const std::shared_ptr<double> &Restaurants::getLongitude() const noexcept
{
    return longitude_;
}
void Restaurants::setLongitude(const double &pLongitude) noexcept
{
    longitude_ = std::make_shared<double>(pLongitude);
    dirtyFlag_[11] = true;
}
void Restaurants::setLongitudeToNull() noexcept
{
    longitude_.reset();
    dirtyFlag_[11] = true;
}

const ::trantor::Date &Restaurants::getValueOfLastUpdated() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(lastUpdated_)
        return *lastUpdated_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &Restaurants::getLastUpdated() const noexcept
{
    return lastUpdated_;
}
void Restaurants::setLastUpdated(const ::trantor::Date &pLastUpdated) noexcept
{
    lastUpdated_ = std::make_shared<::trantor::Date>(pLastUpdated);
    dirtyFlag_[12] = true;
}
void Restaurants::setLastUpdatedToNull() noexcept
{
    lastUpdated_.reset();
    dirtyFlag_[12] = true;
}

void Restaurants::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Restaurants::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "camis",
        "name",
        "boro",
        "building",
        "street",
        "zipcode",
        "phone",
        "cuisine",
        "inspection_date",
        "grade",
        "latitude",
        "longitude",
        "last_updated"
    };
    return inCols;
}

void Restaurants::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getCamis())
        {
            binder << getValueOfCamis();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getName())
        {
            binder << getValueOfName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getBoro())
        {
            binder << getValueOfBoro();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getBuilding())
        {
            binder << getValueOfBuilding();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getStreet())
        {
            binder << getValueOfStreet();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getZipcode())
        {
            binder << getValueOfZipcode();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getPhone())
        {
            binder << getValueOfPhone();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getCuisine())
        {
            binder << getValueOfCuisine();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getInspectionDate())
        {
            binder << getValueOfInspectionDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getGrade())
        {
            binder << getValueOfGrade();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getLatitude())
        {
            binder << getValueOfLatitude();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getLongitude())
        {
            binder << getValueOfLongitude();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getLastUpdated())
        {
            binder << getValueOfLastUpdated();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Restaurants::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    if(dirtyFlag_[10])
    {
        ret.push_back(getColumnName(10));
    }
    if(dirtyFlag_[11])
    {
        ret.push_back(getColumnName(11));
    }
    if(dirtyFlag_[12])
    {
        ret.push_back(getColumnName(12));
    }
    return ret;
}

void Restaurants::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getCamis())
        {
            binder << getValueOfCamis();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getName())
        {
            binder << getValueOfName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getBoro())
        {
            binder << getValueOfBoro();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getBuilding())
        {
            binder << getValueOfBuilding();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getStreet())
        {
            binder << getValueOfStreet();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getZipcode())
        {
            binder << getValueOfZipcode();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getPhone())
        {
            binder << getValueOfPhone();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getCuisine())
        {
            binder << getValueOfCuisine();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getInspectionDate())
        {
            binder << getValueOfInspectionDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getGrade())
        {
            binder << getValueOfGrade();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getLatitude())
        {
            binder << getValueOfLatitude();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getLongitude())
        {
            binder << getValueOfLongitude();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getLastUpdated())
        {
            binder << getValueOfLastUpdated();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Restaurants::toJson() const
{
    Json::Value ret;
    if(getCamis())
    {
        ret["camis"]=getValueOfCamis();
    }
    else
    {
        ret["camis"]=Json::Value();
    }
    if(getName())
    {
        ret["name"]=getValueOfName();
    }
    else
    {
        ret["name"]=Json::Value();
    }
    if(getBoro())
    {
        ret["boro"]=getValueOfBoro();
    }
    else
    {
        ret["boro"]=Json::Value();
    }
    if(getBuilding())
    {
        ret["building"]=getValueOfBuilding();
    }
    else
    {
        ret["building"]=Json::Value();
    }
    if(getStreet())
    {
        ret["street"]=getValueOfStreet();
    }
    else
    {
        ret["street"]=Json::Value();
    }
    if(getZipcode())
    {
        ret["zipcode"]=getValueOfZipcode();
    }
    else
    {
        ret["zipcode"]=Json::Value();
    }
    if(getPhone())
    {
        ret["phone"]=getValueOfPhone();
    }
    else
    {
        ret["phone"]=Json::Value();
    }
    if(getCuisine())
    {
        ret["cuisine"]=getValueOfCuisine();
    }
    else
    {
        ret["cuisine"]=Json::Value();
    }
    if(getInspectionDate())
    {
        ret["inspection_date"]=getInspectionDate()->toDbStringLocal();
    }
    else
    {
        ret["inspection_date"]=Json::Value();
    }
    if(getGrade())
    {
        ret["grade"]=getValueOfGrade();
    }
    else
    {
        ret["grade"]=Json::Value();
    }
    if(getLatitude())
    {
        ret["latitude"]=getValueOfLatitude();
    }
    else
    {
        ret["latitude"]=Json::Value();
    }
    if(getLongitude())
    {
        ret["longitude"]=getValueOfLongitude();
    }
    else
    {
        ret["longitude"]=Json::Value();
    }
    if(getLastUpdated())
    {
        ret["last_updated"]=getLastUpdated()->toDbStringLocal();
    }
    else
    {
        ret["last_updated"]=Json::Value();
    }
    return ret;
}

std::string Restaurants::toString() const
{
    return toJson().toStyledString();
}

Json::Value Restaurants::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 13)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getCamis())
            {
                ret[pMasqueradingVector[0]]=getValueOfCamis();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getName())
            {
                ret[pMasqueradingVector[1]]=getValueOfName();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getBoro())
            {
                ret[pMasqueradingVector[2]]=getValueOfBoro();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getBuilding())
            {
                ret[pMasqueradingVector[3]]=getValueOfBuilding();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getStreet())
            {
                ret[pMasqueradingVector[4]]=getValueOfStreet();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getZipcode())
            {
                ret[pMasqueradingVector[5]]=getValueOfZipcode();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getPhone())
            {
                ret[pMasqueradingVector[6]]=getValueOfPhone();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getCuisine())
            {
                ret[pMasqueradingVector[7]]=getValueOfCuisine();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getInspectionDate())
            {
                ret[pMasqueradingVector[8]]=getInspectionDate()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getGrade())
            {
                ret[pMasqueradingVector[9]]=getValueOfGrade();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[10].empty())
        {
            if(getLatitude())
            {
                ret[pMasqueradingVector[10]]=getValueOfLatitude();
            }
            else
            {
                ret[pMasqueradingVector[10]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[11].empty())
        {
            if(getLongitude())
            {
                ret[pMasqueradingVector[11]]=getValueOfLongitude();
            }
            else
            {
                ret[pMasqueradingVector[11]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[12].empty())
        {
            if(getLastUpdated())
            {
                ret[pMasqueradingVector[12]]=getLastUpdated()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[12]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getCamis())
    {
        ret["camis"]=getValueOfCamis();
    }
    else
    {
        ret["camis"]=Json::Value();
    }
    if(getName())
    {
        ret["name"]=getValueOfName();
    }
    else
    {
        ret["name"]=Json::Value();
    }
    if(getBoro())
    {
        ret["boro"]=getValueOfBoro();
    }
    else
    {
        ret["boro"]=Json::Value();
    }
    if(getBuilding())
    {
        ret["building"]=getValueOfBuilding();
    }
    else
    {
        ret["building"]=Json::Value();
    }
    if(getStreet())
    {
        ret["street"]=getValueOfStreet();
    }
    else
    {
        ret["street"]=Json::Value();
    }
    if(getZipcode())
    {
        ret["zipcode"]=getValueOfZipcode();
    }
    else
    {
        ret["zipcode"]=Json::Value();
    }
    if(getPhone())
    {
        ret["phone"]=getValueOfPhone();
    }
    else
    {
        ret["phone"]=Json::Value();
    }
    if(getCuisine())
    {
        ret["cuisine"]=getValueOfCuisine();
    }
    else
    {
        ret["cuisine"]=Json::Value();
    }
    if(getInspectionDate())
    {
        ret["inspection_date"]=getInspectionDate()->toDbStringLocal();
    }
    else
    {
        ret["inspection_date"]=Json::Value();
    }
    if(getGrade())
    {
        ret["grade"]=getValueOfGrade();
    }
    else
    {
        ret["grade"]=Json::Value();
    }
    if(getLatitude())
    {
        ret["latitude"]=getValueOfLatitude();
    }
    else
    {
        ret["latitude"]=Json::Value();
    }
    if(getLongitude())
    {
        ret["longitude"]=getValueOfLongitude();
    }
    else
    {
        ret["longitude"]=Json::Value();
    }
    if(getLastUpdated())
    {
        ret["last_updated"]=getLastUpdated()->toDbStringLocal();
    }
    else
    {
        ret["last_updated"]=Json::Value();
    }
    return ret;
}

bool Restaurants::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("camis"))
    {
        if(!validJsonOfField(0, "camis", pJson["camis"], err, true))
            return false;
    }
    else
    {
        err="The camis column cannot be null";
        return false;
    }
    if(pJson.isMember("name"))
    {
        if(!validJsonOfField(1, "name", pJson["name"], err, true))
            return false;
    }
    if(pJson.isMember("boro"))
    {
        if(!validJsonOfField(2, "boro", pJson["boro"], err, true))
            return false;
    }
    if(pJson.isMember("building"))
    {
        if(!validJsonOfField(3, "building", pJson["building"], err, true))
            return false;
    }
    if(pJson.isMember("street"))
    {
        if(!validJsonOfField(4, "street", pJson["street"], err, true))
            return false;
    }
    if(pJson.isMember("zipcode"))
    {
        if(!validJsonOfField(5, "zipcode", pJson["zipcode"], err, true))
            return false;
    }
    if(pJson.isMember("phone"))
    {
        if(!validJsonOfField(6, "phone", pJson["phone"], err, true))
            return false;
    }
    if(pJson.isMember("cuisine"))
    {
        if(!validJsonOfField(7, "cuisine", pJson["cuisine"], err, true))
            return false;
    }
    if(pJson.isMember("inspection_date"))
    {
        if(!validJsonOfField(8, "inspection_date", pJson["inspection_date"], err, true))
            return false;
    }
    if(pJson.isMember("grade"))
    {
        if(!validJsonOfField(9, "grade", pJson["grade"], err, true))
            return false;
    }
    if(pJson.isMember("latitude"))
    {
        if(!validJsonOfField(10, "latitude", pJson["latitude"], err, true))
            return false;
    }
    if(pJson.isMember("longitude"))
    {
        if(!validJsonOfField(11, "longitude", pJson["longitude"], err, true))
            return false;
    }
    if(pJson.isMember("last_updated"))
    {
        if(!validJsonOfField(12, "last_updated", pJson["last_updated"], err, true))
            return false;
    }
    return true;
}
bool Restaurants::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                     const std::vector<std::string> &pMasqueradingVector,
                                                     std::string &err)
{
    if(pMasqueradingVector.size() != 13)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[10].empty())
      {
          if(pJson.isMember(pMasqueradingVector[10]))
          {
              if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[11].empty())
      {
          if(pJson.isMember(pMasqueradingVector[11]))
          {
              if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[12].empty())
      {
          if(pJson.isMember(pMasqueradingVector[12]))
          {
              if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Restaurants::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("camis"))
    {
        if(!validJsonOfField(0, "camis", pJson["camis"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("name"))
    {
        if(!validJsonOfField(1, "name", pJson["name"], err, false))
            return false;
    }
    if(pJson.isMember("boro"))
    {
        if(!validJsonOfField(2, "boro", pJson["boro"], err, false))
            return false;
    }
    if(pJson.isMember("building"))
    {
        if(!validJsonOfField(3, "building", pJson["building"], err, false))
            return false;
    }
    if(pJson.isMember("street"))
    {
        if(!validJsonOfField(4, "street", pJson["street"], err, false))
            return false;
    }
    if(pJson.isMember("zipcode"))
    {
        if(!validJsonOfField(5, "zipcode", pJson["zipcode"], err, false))
            return false;
    }
    if(pJson.isMember("phone"))
    {
        if(!validJsonOfField(6, "phone", pJson["phone"], err, false))
            return false;
    }
    if(pJson.isMember("cuisine"))
    {
        if(!validJsonOfField(7, "cuisine", pJson["cuisine"], err, false))
            return false;
    }
    if(pJson.isMember("inspection_date"))
    {
        if(!validJsonOfField(8, "inspection_date", pJson["inspection_date"], err, false))
            return false;
    }
    if(pJson.isMember("grade"))
    {
        if(!validJsonOfField(9, "grade", pJson["grade"], err, false))
            return false;
    }
    if(pJson.isMember("latitude"))
    {
        if(!validJsonOfField(10, "latitude", pJson["latitude"], err, false))
            return false;
    }
    if(pJson.isMember("longitude"))
    {
        if(!validJsonOfField(11, "longitude", pJson["longitude"], err, false))
            return false;
    }
    if(pJson.isMember("last_updated"))
    {
        if(!validJsonOfField(12, "last_updated", pJson["last_updated"], err, false))
            return false;
    }
    return true;
}
bool Restaurants::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                   const std::vector<std::string> &pMasqueradingVector,
                                                   std::string &err)
{
    if(pMasqueradingVector.size() != 13)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
      if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
      {
          if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, false))
              return false;
      }
      if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
      {
          if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, false))
              return false;
      }
      if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
      {
          if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Restaurants::validJsonOfField(size_t index,
                                   const std::string &fieldName,
                                   const Json::Value &pJson,
                                   std::string &err,
                                   bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 9:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 10:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isNumeric())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 11:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isNumeric())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 12:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
