/**
 *
 *  Restaurants.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace biteful
{

class Restaurants
{
  public:
    struct Cols
    {
        static const std::string _camis;
        static const std::string _name;
        static const std::string _boro;
        static const std::string _building;
        static const std::string _street;
        static const std::string _zipcode;
        static const std::string _phone;
        static const std::string _cuisine;
        static const std::string _inspection_date;
        static const std::string _grade;
        static const std::string _latitude;
        static const std::string _longitude;
        static const std::string _last_updated;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = int32_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit Restaurants(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit Restaurants(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    Restaurants(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    Restaurants() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column camis  */
    ///Get the value of the column camis, returns the default value if the column is null
    const int32_t &getValueOfCamis() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getCamis() const noexcept;
    ///Set the value of the column camis
    void setCamis(const int32_t &pCamis) noexcept;

    /**  For column name  */
    ///Get the value of the column name, returns the default value if the column is null
    const std::string &getValueOfName() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getName() const noexcept;
    ///Set the value of the column name
    void setName(const std::string &pName) noexcept;
    void setName(std::string &&pName) noexcept;
    void setNameToNull() noexcept;

    /**  For column boro  */
    ///Get the value of the column boro, returns the default value if the column is null
    const std::string &getValueOfBoro() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getBoro() const noexcept;
    ///Set the value of the column boro
    void setBoro(const std::string &pBoro) noexcept;
    void setBoro(std::string &&pBoro) noexcept;
    void setBoroToNull() noexcept;

    /**  For column building  */
    ///Get the value of the column building, returns the default value if the column is null
    const std::string &getValueOfBuilding() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getBuilding() const noexcept;
    ///Set the value of the column building
    void setBuilding(const std::string &pBuilding) noexcept;
    void setBuilding(std::string &&pBuilding) noexcept;
    void setBuildingToNull() noexcept;

    /**  For column street  */
    ///Get the value of the column street, returns the default value if the column is null
    const std::string &getValueOfStreet() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getStreet() const noexcept;
    ///Set the value of the column street
    void setStreet(const std::string &pStreet) noexcept;
    void setStreet(std::string &&pStreet) noexcept;
    void setStreetToNull() noexcept;

    /**  For column zipcode  */
    ///Get the value of the column zipcode, returns the default value if the column is null
    const std::string &getValueOfZipcode() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getZipcode() const noexcept;
    ///Set the value of the column zipcode
    void setZipcode(const std::string &pZipcode) noexcept;
    void setZipcode(std::string &&pZipcode) noexcept;
    void setZipcodeToNull() noexcept;

    /**  For column phone  */
    ///Get the value of the column phone, returns the default value if the column is null
    const std::string &getValueOfPhone() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getPhone() const noexcept;
    ///Set the value of the column phone
    void setPhone(const std::string &pPhone) noexcept;
    void setPhone(std::string &&pPhone) noexcept;
    void setPhoneToNull() noexcept;

    /**  For column cuisine  */
    ///Get the value of the column cuisine, returns the default value if the column is null
    const std::string &getValueOfCuisine() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getCuisine() const noexcept;
    ///Set the value of the column cuisine
    void setCuisine(const std::string &pCuisine) noexcept;
    void setCuisine(std::string &&pCuisine) noexcept;
    void setCuisineToNull() noexcept;

    /**  For column inspection_date  */
    ///Get the value of the column inspection_date, returns the default value if the column is null
    const ::trantor::Date &getValueOfInspectionDate() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getInspectionDate() const noexcept;
    ///Set the value of the column inspection_date
    void setInspectionDate(const ::trantor::Date &pInspectionDate) noexcept;
    void setInspectionDateToNull() noexcept;

    /**  For column grade  */
    ///Get the value of the column grade, returns the default value if the column is null
    const std::string &getValueOfGrade() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getGrade() const noexcept;
    ///Set the value of the column grade
    void setGrade(const std::string &pGrade) noexcept;
    void setGrade(std::string &&pGrade) noexcept;
    void setGradeToNull() noexcept;

    /**  For column latitude  */
    ///Get the value of the column latitude, returns the default value if the column is null
    const double &getValueOfLatitude() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<double> &getLatitude() const noexcept;
    ///Set the value of the column latitude
    void setLatitude(const double &pLatitude) noexcept;
    void setLatitudeToNull() noexcept;

    /**  For column longitude  */
    ///Get the value of the column longitude, returns the default value if the column is null
    const double &getValueOfLongitude() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<double> &getLongitude() const noexcept;
    ///Set the value of the column longitude
    void setLongitude(const double &pLongitude) noexcept;
    void setLongitudeToNull() noexcept;

    /**  For column last_updated  */
    ///Get the value of the column last_updated, returns the default value if the column is null
    const ::trantor::Date &getValueOfLastUpdated() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getLastUpdated() const noexcept;
    ///Set the value of the column last_updated
    void setLastUpdated(const ::trantor::Date &pLastUpdated) noexcept;
    void setLastUpdatedToNull() noexcept;


    static size_t getColumnNumber() noexcept {  return 13;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<Restaurants>;
    friend drogon::orm::BaseBuilder<Restaurants, true, true>;
    friend drogon::orm::BaseBuilder<Restaurants, true, false>;
    friend drogon::orm::BaseBuilder<Restaurants, false, true>;
    friend drogon::orm::BaseBuilder<Restaurants, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<Restaurants>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<int32_t> camis_;
    std::shared_ptr<std::string> name_;
    std::shared_ptr<std::string> boro_;
    std::shared_ptr<std::string> building_;
    std::shared_ptr<std::string> street_;
    std::shared_ptr<std::string> zipcode_;
    std::shared_ptr<std::string> phone_;
    std::shared_ptr<std::string> cuisine_;
    std::shared_ptr<::trantor::Date> inspectionDate_;
    std::shared_ptr<std::string> grade_;
    std::shared_ptr<double> latitude_;
    std::shared_ptr<double> longitude_;
    std::shared_ptr<::trantor::Date> lastUpdated_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[13]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where camis = $1";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where camis = $1";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
        if(dirtyFlag_[0])
        {
            sql += "camis,";
            ++parametersCount;
        }
        if(dirtyFlag_[1])
        {
            sql += "name,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "boro,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "building,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "street,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "zipcode,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "phone,";
            ++parametersCount;
        }
        if(dirtyFlag_[7])
        {
            sql += "cuisine,";
            ++parametersCount;
        }
        if(dirtyFlag_[8])
        {
            sql += "inspection_date,";
            ++parametersCount;
        }
        if(dirtyFlag_[9])
        {
            sql += "grade,";
            ++parametersCount;
        }
        if(dirtyFlag_[10])
        {
            sql += "latitude,";
            ++parametersCount;
        }
        if(dirtyFlag_[11])
        {
            sql += "longitude,";
            ++parametersCount;
        }
        sql += "last_updated,";
        ++parametersCount;
        if(!dirtyFlag_[12])
        {
            needSelection=true;
        }
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        if(dirtyFlag_[0])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[1])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[2])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[3])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[4])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[5])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[6])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[7])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[8])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[9])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[10])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[11])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[12])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace biteful
} // namespace drogon_model
